#' R Code Execution Backend
#'
#' @description
#' A subprocess execution backend for running R code generated by LLMs. Uses
#' callr for process isolation, timeout protection, output capture, and
#' structured result handling.
#'
#' @details
#' RCodeRunner provides:
#' - **Process isolation**: Code runs in a separate R process via callr
#' - **Timeout protection**: Configurable timeout prevents runaway execution
#' - **Output capture**: Captures stdout, stderr, messages, and warnings
#' - **Context passing**: Inject data into the execution environment
#' - **Output limiting**: Truncates large outputs to prevent memory issues
#'
#' Security note: `r_code_runner()` is a **trusted-input-only** backend. callr
#' starts a separate process, but that process retains the host user's file,
#' network, environment, and operating-system permissions. Pattern checks are
#' only defense in depth and can be bypassed. For untrusted inputs, provide a
#' runner backed by a container or OS-level sandbox.
#'
#' Code-executing modules accept any runner that implements the dsprrr runner
#' protocol. A runner must expose `execute(code, context = list())` and
#' `policy()` methods. `policy()` returns a uniquely named list containing at
#' least `backend` (character), `trust` (character), and `sandboxed` (logical).
#' `execute()` returns one uniquely named list. `success` and `result` are
#' required. Missing `stdout`, `stderr`, `messages`, and `warnings` fields are
#' normalized to empty strings, and missing `duration_ms` is normalized to
#' `NA`. A failed result must include a non-empty `error`. Its `error_type` is
#' either `"execution"` for code the model may repair or `"interpreter"` for a
#' terminal process/protocol failure. Legacy runners that omit `error_type` are
#' treated as reporting a repairable execution failure. A successful result
#' may omit `error` and `error_type`.
#'
#' Code-executing modules accept exactly one runtime source. Passing `runner`
#' retains that caller-owned object and never closes it. Passing a zero-argument
#' `interpreter_factory` creates one fresh invocation-owned runner. Factory
#' results may implement idempotent `start()` and must implement idempotent
#' terminal `shutdown()` or its compatibility alias `close()`. dsprrr starts a
#' factory runner before use and shuts it down exactly once on success, error,
#' or interrupt.
#'
#' @examples
#' \dontrun{
#' runner <- r_code_runner(timeout = 5)
#'
#' # Simple execution
#' result <- runner$execute("1 + 1")
#' result$result
#' # [1] 2
#'
#' # With context
#' result <- runner$execute(
#'   "mean(.context$data$mpg)",
#'   context = list(data = mtcars)
#' )
#' result$result
#' # [1] 20.09062
#'
#' # Timeout handling
#' result <- runner$execute("Sys.sleep(100)")
#' result$success
#' # [1] FALSE
#' result$error
#' # "Execution timed out after 5 seconds"
#' }
#'
#' @name r-code-runner
NULL

#' Create an R Code Runner
#'
#' @description
#' Factory function to create a trusted-input-only RCodeRunner instance.
#'
#' @param timeout Numeric. Maximum execution time in seconds. Default 30.
#' @param max_output_chars Integer. Maximum characters for stdout/stderr.
#'   Output exceeding this limit is truncated. Default 100000 (100KB).
#' @param allowed_packages Character vector. Packages that may be loaded.
#'   This is defense-in-depth only; not a security boundary.
#'
#'   Default: c("base", "stats", "utils", "methods").
#' @param prelude Character vector. R code to run before user code.
#'   Useful for setting options or loading common utilities.
#' @param persistent Logical. Whether to reuse one callr session and execution
#'   environment across calls to `execute()`. This preserves variables and
#'   supports staging a base context with `prepare_context()`. Default `FALSE`
#'   preserves one fresh subprocess per execution.
#'
#' @return An RCodeRunner R6 object
#'
#' @export
#' @examples
#' \dontrun{
#' runner <- r_code_runner(timeout = 10)
#' result <- runner$execute("sqrt(16)")
#' result$result
#' # [1] 4
#' }
r_code_runner <- function(
  timeout = 30,
  max_output_chars = 100000L,
  allowed_packages = c("base", "stats", "utils", "methods"),
  prelude = character(),
  persistent = FALSE
) {
  rlang::check_installed("callr", reason = "for code execution")

  RCodeRunner$new(
    timeout = timeout,
    max_output_chars = as.integer(max_output_chars),
    allowed_packages = allowed_packages,
    prelude = prelude,
    persistent = persistent
  )
}


# Validate the structural runner protocol used by code-executing modules.
validate_code_runner <- function(runner) {
  execute <- tryCatch(runner[["execute"]], error = function(e) NULL)
  policy <- tryCatch(runner[["policy"]], error = function(e) NULL)

  if (!is.function(execute) || !is.function(policy)) {
    cli::cli_abort(
      c(
        "runner must implement the dsprrr code-runner protocol",
        "x" = "A runner needs {.code execute(code, context)} and {.code policy()} methods.",
        "i" = "Use {.code r_code_runner()} for trusted inputs or provide a sandboxed backend."
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  runner_policy <- tryCatch(
    policy(),
    error = function(e) {
      cli::cli_abort(
        c(
          "runner$policy() failed",
          "x" = conditionMessage(e)
        ),
        class = "dsprrr_code_runner_protocol_error"
      )
    }
  )
  policy_names <- names(runner_policy)
  required <- c("backend", "trust", "sandboxed")
  missing_fields <- setdiff(required, policy_names)

  valid_names <- is.list(runner_policy) &&
    !is.null(policy_names) &&
    !anyNA(policy_names) &&
    all(nzchar(policy_names)) &&
    !anyDuplicated(policy_names)
  if (!valid_names || length(missing_fields) > 0) {
    cli::cli_abort(
      c(
        "runner$policy() must return a uniquely named list",
        "x" = "Missing required fields: {.field {missing_fields}}",
        "i" = "Required fields are {.field backend}, {.field trust}, and {.field sandboxed}."
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  valid_backend <- is.character(runner_policy$backend) &&
    length(runner_policy$backend) == 1L &&
    !is.na(runner_policy$backend) &&
    nzchar(runner_policy$backend)
  valid_trust <- is.character(runner_policy$trust) &&
    length(runner_policy$trust) == 1L &&
    !is.na(runner_policy$trust) &&
    nzchar(runner_policy$trust)
  valid_sandboxed <- is.logical(runner_policy$sandboxed) &&
    length(runner_policy$sandboxed) == 1L &&
    !is.na(runner_policy$sandboxed)

  if (!valid_backend || !valid_trust || !valid_sandboxed) {
    cli::cli_abort(
      c(
        "runner$policy() returned invalid metadata",
        "i" = "{.field backend} and {.field trust} must be non-empty strings.",
        "i" = "{.field sandboxed} must be TRUE or FALSE."
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  invisible(runner_policy)
}


summarize_code_runner_policy <- function(policy) {
  list(
    backend = policy$backend,
    trust = policy$trust,
    sandboxed = policy$sandboxed,
    persistent = if (
      is.logical(policy$persistent) &&
        length(policy$persistent) == 1L &&
        !is.na(policy$persistent)
    ) {
      policy$persistent
    } else {
      NA
    }
  )
}


validate_code_runner_result <- function(result) {
  result_names <- names(result)
  if (
    !is.list(result) ||
      is.null(result_names) ||
      anyNA(result_names) ||
      !all(nzchar(result_names)) ||
      anyDuplicated(result_names)
  ) {
    cli::cli_abort(
      "runner$execute() must return one named result list",
      class = "dsprrr_code_runner_protocol_error"
    )
  }
  required <- c("success", "result")
  missing <- setdiff(required, names(result))
  if (length(missing) > 0L) {
    cli::cli_abort(
      c(
        "runner$execute() returned an incomplete result",
        "x" = "Missing field{?s}: {.field {missing}}"
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }
  if (
    !is.logical(result$success) ||
      length(result$success) != 1L ||
      is.na(result$success)
  ) {
    cli::cli_abort(
      "runner$execute() field {.field success} must be TRUE or FALSE",
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  normalize_text <- function(name) {
    value <- result[[name]]
    if (is.null(value)) {
      return("")
    }
    if (!is.character(value) || length(value) != 1L || is.na(value)) {
      cli::cli_abort(
        "runner$execute() field {.field {name}} must be one non-missing string",
        class = "dsprrr_code_runner_protocol_error"
      )
    }
    value
  }
  for (name in c("stdout", "stderr", "messages", "warnings")) {
    result[[name]] <- normalize_text(name)
  }

  error <- result$error
  if (isTRUE(result$success)) {
    if (
      !is.null(error) &&
        (!is.character(error) ||
          length(error) != 1L ||
          is.na(error))
    ) {
      cli::cli_abort(
        "runner$execute() field {.field error} must be NULL or one string",
        class = "dsprrr_code_runner_protocol_error"
      )
    }
  } else if (
    !is.character(error) ||
      length(error) != 1L ||
      is.na(error) ||
      !nzchar(error)
  ) {
    cli::cli_abort(
      "A failed runner result must contain one non-empty {.field error}",
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  error_type <- result$error_type
  if (isTRUE(result$success)) {
    if (!is.null(error_type)) {
      cli::cli_abort(
        "A successful runner result must not contain {.field error_type}",
        class = "dsprrr_code_runner_protocol_error"
      )
    }
  } else {
    error_type <- error_type %||% "execution"
    if (
      !is.character(error_type) ||
        length(error_type) != 1L ||
        is.na(error_type) ||
        !error_type %in% c("execution", "interpreter")
    ) {
      cli::cli_abort(
        "A failed runner result field {.field error_type} must be {.val execution} or {.val interpreter}",
        class = "dsprrr_code_runner_protocol_error"
      )
    }
  }

  duration <- result$duration_ms
  if (is.null(duration)) {
    result$duration_ms <- NA_real_
  } else if (
    !is.numeric(duration) ||
      length(duration) != 1L ||
      (!is.na(duration) && (!is.finite(duration) || duration < 0))
  ) {
    cli::cli_abort(
      "runner$execute() field {.field duration_ms} must be one non-negative number or NA",
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  result$error <- error %||% NULL
  result$error_type <- error_type %||% NULL
  retryable <- !isTRUE(result$success) &&
    identical(error_type, "execution")
  if (
    !is.null(result$retryable) &&
      (!is.logical(result$retryable) ||
        length(result$retryable) != 1L ||
        is.na(result$retryable) ||
        !identical(result$retryable, retryable))
  ) {
    cli::cli_abort(
      "runner$execute() field {.field retryable} is inconsistent with {.field success} and {.field error_type}",
      class = "dsprrr_code_runner_protocol_error"
    )
  }
  result$retryable <- retryable
  result
}


abort_terminal_code_runner_result <- function(result) {
  cli::cli_abort(
    c(
      "The code interpreter session failed and cannot be reused",
      "x" = result$error,
      "i" = "Create a fresh interpreter before retrying the module."
    ),
    class = c(
      "dsprrr_code_interpreter_error",
      "dsprrr_interpreter_terminal_error"
    ),
    runner_result = result
  )
}


is_terminal_interpreter_condition <- function(condition) {
  inherits(
    condition,
    c(
      "dsprrr_code_interpreter_error",
      "dsprrr_interpreter_terminal_error",
      "dsprrr_interpreter_closed_error",
      "dsprrr_code_runner_protocol_error"
    )
  )
}


execute_code_runner <- function(
  runner,
  code,
  context = list(),
  .control_nonce = NULL,
  .control_protocol = NULL,
  .control_max_bytes = NULL
) {
  execute_args <- list(code = code, context = context)
  execute_formals <- tryCatch(
    names(formals(runner$execute)),
    error = function(e) character()
  )
  accepts_dots <- "..." %in% execute_formals
  control_args <- list(
    .control_nonce = .control_nonce,
    .control_protocol = .control_protocol,
    .control_max_bytes = .control_max_bytes
  )
  for (name in names(control_args)) {
    if (
      !is.null(control_args[[name]]) &&
        (name %in% execute_formals || accepts_dots)
    ) {
      execute_args[[name]] <- control_args[[name]]
    }
  }
  result <- tryCatch(
    do.call(runner$execute, execute_args),
    interrupt = function(condition) stop(condition),
    error = function(condition) {
      if (is_terminal_interpreter_condition(condition)) {
        stop(condition)
      }
      cli::cli_abort(
        c(
          "The code interpreter failed outside submitted-code execution",
          "x" = conditionMessage(condition),
          "i" = "A runner must return repairable code failures as a typed result instead of signalling them."
        ),
        class = c(
          "dsprrr_code_interpreter_error",
          "dsprrr_interpreter_terminal_error"
        ),
        parent = condition
      )
    }
  )
  result <- validate_code_runner_result(result)
  if (
    !isTRUE(result$success) &&
      identical(result$error_type, "interpreter")
  ) {
    abort_terminal_code_runner_result(result)
  }
  result
}


# Validate the zero-argument factory contract used by code-executing modules.
# The factory is deliberately not invoked during module construction: creating
# an interpreter may start a process or open a network connection.
validate_interpreter_factory <- function(interpreter_factory) {
  if (!is.function(interpreter_factory)) {
    cli::cli_abort(
      "{.arg interpreter_factory} must be a zero-argument function",
      class = "dsprrr_interpreter_factory_error"
    )
  }

  if (is.primitive(interpreter_factory)) {
    cli::cli_abort(
      "{.arg interpreter_factory} must have an inspectable zero-argument signature",
      class = "dsprrr_interpreter_factory_error"
    )
  }

  factory_formals <- tryCatch(
    formals(interpreter_factory),
    error = function(e) NULL
  )

  required <- names(factory_formals)[vapply(
    factory_formals,
    identical,
    logical(1),
    quote(expr = )
  )]
  required <- setdiff(required, "...")
  if (length(required) > 0L) {
    cli::cli_abort(
      c(
        "{.arg interpreter_factory} must be callable without arguments",
        "x" = "Required argument{?s}: {.arg {required}}"
      ),
      class = "dsprrr_interpreter_factory_error"
    )
  }

  invisible(interpreter_factory)
}


validate_interpreter_lifecycle_method <- function(method, name) {
  if (!is.function(method)) {
    cli::cli_abort(
      c(
        "{.arg interpreter_factory} returned a runner without a callable {.code {name}()}",
        "i" = "Invocation-owned runners must expose an idempotent terminal {.code shutdown()} or {.code close()} method."
      ),
      class = "dsprrr_interpreter_factory_error"
    )
  }
  if (is.primitive(method)) {
    cli::cli_abort(
      "A factory-created runner's {.code {name}()} must have an inspectable zero-argument signature",
      class = "dsprrr_interpreter_factory_error"
    )
  }

  method_formals <- tryCatch(formals(method), error = function(e) NULL)
  required <- names(method_formals)[vapply(
    method_formals,
    identical,
    logical(1),
    quote(expr = )
  )]
  required <- setdiff(required, "...")
  if (length(required) > 0L) {
    cli::cli_abort(
      c(
        "A factory-created runner's {.code {name}()} must be callable without arguments",
        "x" = "Required argument{?s}: {.arg {required}}",
        "i" = "The module will not execute with a runner whose cleanup contract is invalid."
      ),
      class = "dsprrr_interpreter_factory_error"
    )
  }

  invisible(method)
}


validate_interpreter_close <- function(close) {
  validate_interpreter_lifecycle_method(close, "close")
}


interpreter_cleanup_method <- function(runner, required = TRUE) {
  shutdown <- tryCatch(runner[["shutdown"]], error = function(e) NULL)
  close <- tryCatch(runner[["close"]], error = function(e) NULL)
  candidates <- list(shutdown = shutdown, close = close)
  validation_errors <- list()
  for (name in names(candidates)) {
    method <- candidates[[name]]
    if (!is.function(method)) {
      next
    }
    validation <- tryCatch(
      {
        validate_interpreter_lifecycle_method(method, name)
        NULL
      },
      interrupt = function(condition) stop(condition),
      error = function(condition) condition
    )
    if (is.null(validation)) {
      return(list(fun = method, name = name))
    }
    validation_errors[[name]] <- validation
  }
  if (length(validation_errors) > 0L && isTRUE(required)) {
    stop(validation_errors[[1L]])
  }
  if (isTRUE(required)) {
    cli::cli_abort(
      c(
        "{.arg interpreter_factory} returned a runner without terminal cleanup",
        "i" = "Implement idempotent {.code shutdown()} or {.code close()}."
      ),
      class = "dsprrr_interpreter_factory_error"
    )
  }
  NULL
}


best_effort_interpreter_cleanup <- function(runner) {
  method <- tryCatch(
    interpreter_cleanup_method(runner, required = FALSE),
    error = function(e) NULL
  )
  if (is.null(method)) {
    return(NULL)
  }
  tryCatch(
    {
      method$fun()
      NULL
    },
    interrupt = function(e) e,
    error = function(e) e
  )
}


start_factory_interpreter <- function(runner, module_name) {
  start <- tryCatch(runner[["start"]], error = function(e) NULL)
  if (!is.function(start)) {
    return(invisible(runner))
  }
  validate_interpreter_lifecycle_method(start, "start")
  tryCatch(
    {
      start()
      invisible(runner)
    },
    interrupt = function(e) stop(e),
    error = function(e) {
      cli::cli_abort(
        "{module_name} could not start its invocation-owned interpreter",
        parent = e,
        class = "dsprrr_interpreter_start_error"
      )
    }
  )
}


# Normalize a constructor's mutually exclusive runtime choices without opening
# a factory-created interpreter.
normalize_code_runner_binding <- function(
  runner = NULL,
  interpreter_factory = NULL,
  module_name = "Code execution"
) {
  if (is.null(runner) && is.null(interpreter_factory)) {
    cli::cli_abort(
      c(
        "{module_name} requires an explicit runner or interpreter_factory",
        "i" = "Use {.code runner = r_code_runner()} for a caller-owned runner.",
        "i" = "Use {.code interpreter_factory = r_code_runner} for a fresh runner per invocation."
      ),
      class = "dsprrr_interpreter_binding_error"
    )
  }
  if (!is.null(runner) && !is.null(interpreter_factory)) {
    cli::cli_abort(
      "Supply only one of {.arg runner} and {.arg interpreter_factory}",
      class = "dsprrr_interpreter_binding_error"
    )
  }

  if (!is.null(runner)) {
    validate_code_runner(runner)
    return(list(
      runner = runner,
      interpreter_factory = NULL,
      lifecycle = "caller-owned"
    ))
  }

  validate_interpreter_factory(interpreter_factory)
  list(
    runner = NULL,
    interpreter_factory = interpreter_factory,
    lifecycle = "invocation-owned"
  )
}


# Acquire one runtime interpreter. Factory-created runners must expose close()
# because the module, rather than the caller, owns their lifecycle.
acquire_code_runner <- function(runner, interpreter_factory, module_name) {
  if (is.null(runner) == is.null(interpreter_factory)) {
    cli::cli_abort(
      "{module_name} must have exactly one of {.arg runner} and {.arg interpreter_factory}",
      class = "dsprrr_interpreter_binding_error"
    )
  }
  if (!is.null(runner)) {
    runner_policy <- validate_code_runner(runner)
    return(list(
      runner = runner,
      owned = FALSE,
      policy = runner_policy,
      policy_summary = summarize_code_runner_policy(runner_policy),
      module_name = module_name
    ))
  }

  validate_interpreter_factory(interpreter_factory)
  created <- tryCatch(
    interpreter_factory(),
    error = function(e) {
      cli::cli_abort(
        "{module_name} could not create an interpreter",
        parent = e,
        class = "dsprrr_interpreter_factory_error"
      )
    }
  )
  validation <- tryCatch(
    validate_code_runner(created),
    interrupt = function(e) e,
    error = function(e) e
  )
  if (inherits(validation, "condition")) {
    close_error <- best_effort_interpreter_cleanup(created)
    if (inherits(close_error, "condition")) {
      attr(validation, "dsprrr_interpreter_close_error") <- close_error
    }
    if (inherits(validation, "interrupt")) {
      stop(validation)
    }
    cli::cli_abort(
      "{.arg interpreter_factory} returned an invalid runner",
      parent = validation,
      class = "dsprrr_interpreter_factory_error"
    )
  }
  runner_policy <- validation
  cleanup <- tryCatch(
    interpreter_cleanup_method(created),
    interrupt = function(e) e,
    error = function(e) e
  )
  if (inherits(cleanup, "condition")) {
    cleanup_error <- best_effort_interpreter_cleanup(created)
    if (inherits(cleanup_error, "condition")) {
      attr(cleanup, "dsprrr_interpreter_close_error") <- cleanup_error
    }
    if (inherits(cleanup, "interrupt")) {
      stop(cleanup)
    }
    stop(cleanup)
  }

  start_error <- tryCatch(
    {
      start_factory_interpreter(created, module_name)
      NULL
    },
    interrupt = function(e) e,
    error = function(e) e
  )
  if (inherits(start_error, "condition")) {
    cleanup_error <- tryCatch(
      {
        cleanup$fun()
        NULL
      },
      interrupt = function(e) e,
      error = function(e) e
    )
    if (inherits(cleanup_error, "condition")) {
      attr(start_error, "dsprrr_interpreter_close_error") <- cleanup_error
    }
    stop(start_error)
  }

  list(
    runner = created,
    owned = TRUE,
    cleanup = cleanup$fun,
    cleanup_method = cleanup$name,
    policy = runner_policy,
    policy_summary = summarize_code_runner_policy(runner_policy),
    module_name = module_name
  )
}


# Close one invocation-owned runner and return, rather than signal, any error.
close_code_runner_lease <- function(lease) {
  if (!is.list(lease) || !isTRUE(lease$owned)) {
    return(NULL)
  }
  tryCatch(
    {
      cleanup <- lease$cleanup %||%
        interpreter_cleanup_method(lease$runner)$fun
      cleanup()
      NULL
    },
    interrupt = function(e) e,
    error = function(e) e
  )
}


# Run a module body under one interpreter lease. Cleanup after a successful
# body is part of success and therefore errors if it fails. When execution and
# cleanup both fail, the execution condition remains primary and carries the
# cleanup condition as diagnostic metadata.
with_code_runner_lease <- function(
  runner,
  interpreter_factory,
  module_name,
  code
) {
  if (!is.function(code)) {
    cli::cli_abort("Internal interpreter lease body must be a function")
  }
  lease <- acquire_code_runner(runner, interpreter_factory, module_name)
  outcome <- tryCatch(
    list(ok = TRUE, value = code(lease$runner, lease)),
    interrupt = function(condition) list(ok = FALSE, condition = condition),
    error = function(condition) list(ok = FALSE, condition = condition)
  )
  close_error <- close_code_runner_lease(lease)

  if (!isTRUE(outcome$ok)) {
    if (inherits(close_error, "condition")) {
      attr(outcome$condition, "dsprrr_interpreter_close_error") <- close_error
    }
    stop(outcome$condition)
  }
  if (inherits(close_error, "condition")) {
    cli::cli_abort(
      "{module_name} could not close its invocation-owned interpreter",
      parent = close_error,
      class = "dsprrr_interpreter_close_error"
    )
  }

  outcome$value
}


code_runner_binding_label <- function(runner, interpreter_factory) {
  if (!is.null(interpreter_factory)) {
    return("fresh runner per invocation")
  }
  policy <- tryCatch(runner$policy(), error = function(e) list())
  paste0(policy$backend %||% class(runner)[1L], " (caller-owned)")
}


#' RCodeRunner R6 Class
#'
#' @description
#' R6 class for trusted R code execution in separate subprocesses.
#'
#' TRUST NOTE: This class intentionally uses eval() to execute
#' LLM-generated R code. This is the core purpose of the ProgramOfThought
#' and CodeAct modules. It provides operational safeguards through:
#' 1. Opt-in design (requires explicit runner creation)
#' 2. Subprocess isolation via callr
#' 3. Timeout protection
#' 4. Dangerous pattern scanning (defense in depth)
#'
#' These safeguards do not restrict host permissions and are not a security
#' boundary. For untrusted input, provide a runner backed by OS-level sandboxing.
#'
#' @keywords internal
#' @noRd
RCodeRunner <- R6::R6Class(
  "RCodeRunner",
  public = list(
    #' @field timeout Maximum execution time in seconds
    timeout = NULL,

    #' @field max_output_chars Maximum output size before truncation
    max_output_chars = NULL,

    #' @field allowed_packages Packages allowed to be loaded
    allowed_packages = NULL,

    #' @field prelude Code to run before user code
    prelude = NULL,

    #' @field persistent Whether one subprocess and execution environment persist
    persistent = FALSE,

    #' @field closed Whether this runner has been closed
    closed = FALSE,

    #' @field started Whether lifecycle startup has completed
    started = FALSE,

    #' @field terminal Whether a process or protocol failure made this runner unusable
    terminal = FALSE,

    #' @field terminal_reason Explanation for the terminal state
    terminal_reason = NULL,

    #' @description
    #' Initialize a new RCodeRunner
    #' @param timeout Numeric timeout in seconds
    #' @param max_output_chars Integer max output size
    #' @param allowed_packages Character vector of allowed packages
    #' @param prelude Character vector of prelude code
    #' @param persistent Whether to reuse one subprocess across executions
    initialize = function(
      timeout = 30,
      max_output_chars = 100000L,
      allowed_packages = c("base", "stats", "utils", "methods"),
      prelude = character(),
      persistent = FALSE
    ) {
      self$timeout <- timeout
      self$max_output_chars <- max_output_chars
      self$allowed_packages <- allowed_packages
      self$prelude <- prelude
      if (
        !is.logical(persistent) || length(persistent) != 1L || is.na(persistent)
      ) {
        cli::cli_abort("{.arg persistent} must be TRUE or FALSE")
      }
      self$persistent <- persistent
    },

    #' @description
    #' Execute R code in an isolated subprocess
    #'
    #' @param code Character string of R code to execute
    #' @param context Named list of objects to make available as `.context`
    #'
    #' @return A list with components:
    #'   - `success`: Logical indicating successful execution
    #'   - `result`: The return value of the code (NULL on error)
    #'   - `stdout`: Character string of stdout output
    #'   - `stderr`: Character string of stderr output
    #'   - `messages`: Character string of message() output
    #'   - `warnings`: Character string of warning() output
    #'   - `error`: Error message if failed (NULL on success)
    #'   - `duration_ms`: Execution time in milliseconds
    execute = function(code, context = list()) {
      if (self$closed) {
        cli::cli_abort(
          "The R code runner is closed",
          class = "dsprrr_interpreter_closed_error"
        )
      }
      if (self$terminal) {
        cli::cli_abort(
          c(
            "The R code runner is terminal",
            "x" = self$terminal_reason %||%
              "A subprocess or protocol failure occurred."
          ),
          class = "dsprrr_interpreter_terminal_error"
        )
      }
      if (!is.character(code) || length(code) != 1) {
        cli::cli_abort("code must be a single character string")
      }
      if (!self$started) {
        self$start()
      }

      start_time <- Sys.time()

      # Check for dangerous patterns (defense in depth)
      danger_check <- private$check_dangerous_patterns(code)
      if (!is.null(danger_check)) {
        return(private$error_result(
          error = danger_check,
          duration_ms = 0
        ))
      }

      if (self$persistent) {
        return(private$execute_persistent(
          code = code,
          context = context,
          start_time = start_time
        ))
      }

      # Create temp files for output capture
      stdout_file <- tempfile("stdout_", fileext = ".txt")
      stderr_file <- tempfile("stderr_", fileext = ".txt")
      on.exit(unlink(c(stdout_file, stderr_file)), add = TRUE)

      # Build the execution wrapper
      # Source metadata is not needed in the child. Removing it keeps the
      # serialized worker small and prevents coverage instrumentation from
      # making each callr process load the parent package namespace.
      worker <- utils::removeSource(private$execution_wrapper)
      exec_result <- tryCatch(
        {
          callr::r(
            func = worker,
            args = list(
              code = code,
              context = context,
              prelude = self$prelude,
              allowed_packages = self$allowed_packages,
              stdout_path = stdout_file,
              stderr_path = stderr_file
            ),
            timeout = self$timeout,
            stdout = "|",
            stderr = "|",
            # callr only drains configured output streams when a callback is
            # active. The no-op callback keeps stdout/stderr capture complete
            # without echoing model-generated output in the host process.
            callback = function(output) invisible(NULL),
            user_profile = FALSE,
            env = c(
              callr::rcmd_safe_env(),
              "R_BROWSER" = "false",
              "R_PDFVIEWER" = "false"
            )
          )
        },
        callr_timeout_error = function(e) {
          structure(
            list(
              error = paste0(
                "Execution timed out after ",
                self$timeout,
                " seconds"
              )
            ),
            class = "timeout_error"
          )
        },
        system_command_timeout_error = function(e) {
          structure(
            list(
              error = paste0(
                "Execution timed out after ",
                self$timeout,
                " seconds"
              )
            ),
            class = "timeout_error"
          )
        },
        error = function(e) {
          structure(
            list(error = conditionMessage(e)),
            class = "exec_error"
          )
        }
      )

      duration_ms <- as.numeric(
        difftime(Sys.time(), start_time, units = "secs")
      ) *
        1000

      # Read captured output
      stdout_content <- private$read_output_file(stdout_file)
      stderr_content <- private$read_output_file(stderr_file)

      # Handle different result types
      if (inherits(exec_result, "timeout_error")) {
        return(private$error_result(
          error = exec_result$error,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms
        ))
      }

      if (inherits(exec_result, "exec_error")) {
        private$mark_terminal(exec_result$error)
        return(private$error_result(
          error = exec_result$error,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms,
          error_type = "interpreter"
        ))
      }

      if (
        !is.list(exec_result) ||
          !is.logical(exec_result$success) ||
          length(exec_result$success) != 1L ||
          is.na(exec_result$success)
      ) {
        reason <- paste(
          "The R subprocess returned no valid structured execution result"
        )
        private$mark_terminal(reason)
        return(private$error_result(
          error = reason,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms,
          error_type = "interpreter"
        ))
      }

      # Successful execution - exec_result is the wrapper's return value
      combine_output <- function(primary, fallback) {
        values <- c(primary %||% "", fallback %||% "")
        values <- values[nzchar(values)]
        if (length(values) == 0L) "" else paste(values, collapse = "\n")
      }
      list(
        success = exec_result$success,
        result = exec_result$result,
        stdout = private$truncate_output(combine_output(
          exec_result$stdout,
          stdout_content
        )),
        stderr = private$truncate_output(combine_output(
          exec_result$stderr,
          stderr_content
        )),
        messages = private$truncate_output(exec_result$messages %||% ""),
        warnings = private$truncate_output(exec_result$warnings %||% ""),
        error = exec_result$error,
        error_type = if (isTRUE(exec_result$success)) NULL else "execution",
        retryable = !isTRUE(exec_result$success),
        duration_ms = round(duration_ms, 2)
      )
    },

    #' @description
    #' Start the interpreter lifecycle
    #'
    #' In the default non-persistent mode, startup is an idempotent lifecycle
    #' marker. In persistent mode, it starts and initializes one callr session.
    #'
    #' @return The runner, invisibly
    start = function() {
      if (self$closed) {
        cli::cli_abort(
          "The R code runner is closed",
          class = "dsprrr_interpreter_closed_error"
        )
      }
      if (self$terminal) {
        cli::cli_abort(
          c(
            "The R code runner is terminal",
            "x" = self$terminal_reason %||%
              "A subprocess or protocol failure occurred."
          ),
          class = "dsprrr_interpreter_terminal_error"
        )
      }
      if (self$started) {
        if (self$persistent && !private$session_is_alive()) {
          reason <- "The persistent R subprocess is no longer running"
          private$terminalize_persistent(reason)
          cli::cli_abort(
            c(
              "The R code runner is terminal",
              "x" = reason
            ),
            class = "dsprrr_interpreter_terminal_error"
          )
        }
        return(invisible(self))
      }

      if (self$persistent) {
        startup <- private$start_persistent_session()
        if (!isTRUE(startup$ok)) {
          cli::cli_abort(
            c(
              "Could not start the persistent R code runner",
              "x" = startup$error
            ),
            class = c(
              "dsprrr_r_code_runner_start_error",
              "dsprrr_interpreter_start_error"
            )
          )
        }
      }
      self$started <- TRUE
      invisible(self)
    },

    #' @description
    #' Stage a base context in a persistent subprocess
    #'
    #' Each later `execute()` call overlays its `context` fields on this base
    #' context for that call. The base objects are serialized only while being
    #' prepared, rather than with every execution.
    #'
    #' @param context Named list of base context objects
    #'
    #' @return `TRUE`, invisibly, after the context is staged
    prepare_context = function(context) {
      private$assert_usable()
      if (!self$persistent) {
        cli::cli_abort(
          c(
            "Base context staging requires a persistent R code runner",
            "i" = "Create it with {.code r_code_runner(persistent = TRUE)}."
          ),
          class = "dsprrr_r_code_runner_context_error"
        )
      }
      private$validate_persistent_context(context)
      if (!self$started) {
        self$start()
      }

      outcome <- private$session_call(
        utils::removeSource(private$persistent_prepare_context),
        args = list(context = context)
      )
      if (!isTRUE(outcome$ok)) {
        cli::cli_abort(
          c(
            "Could not prepare the persistent R code runner context",
            "x" = outcome$error
          ),
          class = c(
            "dsprrr_r_code_runner_context_error",
            "dsprrr_interpreter_terminal_error"
          )
        )
      }
      invisible(TRUE)
    },

    #' @description
    #' Release a staged base context without resetting persistent variables
    #'
    #' This clears both the staged base context and the current `.context`
    #' binding. It is an idempotent no-op in non-persistent mode.
    #'
    #' @return The runner, invisibly
    release_context = function() {
      private$assert_usable()
      if (!self$persistent || !self$started) {
        return(invisible(self))
      }

      outcome <- private$session_call(
        utils::removeSource(private$persistent_prepare_context),
        args = list(context = list())
      )
      if (!isTRUE(outcome$ok)) {
        cli::cli_abort(
          c(
            "Could not release the persistent R code runner context",
            "x" = outcome$error
          ),
          class = c(
            "dsprrr_r_code_runner_context_error",
            "dsprrr_interpreter_terminal_error"
          )
        )
      }
      invisible(self)
    },

    #' @description
    #' Reset persistent execution state and staged context
    #'
    #' Recreates the execution environment, reruns the prelude, and clears the
    #' staged base context. This is an idempotent no-op in non-persistent mode.
    #'
    #' @return The runner, invisibly
    reset = function() {
      private$assert_usable()
      if (!self$persistent) {
        return(invisible(self))
      }
      if (!self$started) {
        self$start()
        return(invisible(self))
      }

      outcome <- private$session_call(
        utils::removeSource(private$persistent_reset),
        args = list()
      )
      if (!isTRUE(outcome$ok)) {
        cli::cli_abort(
          c(
            "Could not reset the persistent R code runner",
            "x" = outcome$error
          ),
          class = c(
            "dsprrr_r_code_runner_reset_error",
            "dsprrr_interpreter_terminal_error"
          )
        )
      }
      invisible(self)
    },

    #' @description
    #' Describe the execution backend's trust boundary
    #'
    #' @return A named list implementing the dsprrr runner policy contract
    policy = function() {
      list(
        backend = "callr",
        trust = "trusted-input-only",
        sandboxed = FALSE,
        persistent = self$persistent,
        process_isolation = TRUE,
        filesystem_access = "host-user",
        network_access = "host-user",
        pattern_scan = "defense-in-depth",
        host_tools = "unsupported",
        lifecycle = "start-execute-shutdown"
      )
    },

    #' @description
    #' Close the runner
    #'
    #' Closing marks the object closed and tears down a persistent subprocess,
    #' when present. It is safe to call more than once.
    #'
    #' @return The runner, invisibly
    close = function() {
      if (self$closed) {
        return(invisible(self))
      }
      self$closed <- TRUE
      private$close_persistent_session()
      invisible(self)
    },

    #' @description
    #' Shut down the interpreter lifecycle
    #'
    #' Alias for `RCodeRunner$close()` matching the common interpreter
    #' protocol.
    #'
    #' @return The runner, invisibly
    shutdown = function() {
      self$close()
    },

    #' @description
    #' Print method for RCodeRunner
    print = function() {
      trust <- self$policy()$trust
      cli::cli_h3("RCodeRunner")
      details <- c(
        "*" = "Timeout: {.val {self$timeout}} seconds",
        "*" = "Max output: {.val {self$max_output_chars}} chars",
        "*" = "Allowed packages: {.val {self$allowed_packages}}"
      )
      if (self$persistent) {
        details <- c(
          details,
          "*" = "Persistent session: {.val TRUE}"
        )
      }
      cli::cli_bullets(c(
        details,
        "!" = "Trust: {.val {trust}}; not sandboxed"
      ))
      invisible(self)
    }
  ),

  private = list(
    session = NULL,

    assert_usable = function() {
      if (self$closed) {
        cli::cli_abort(
          "The R code runner is closed",
          class = "dsprrr_interpreter_closed_error"
        )
      }
      if (self$terminal) {
        cli::cli_abort(
          c(
            "The R code runner is terminal",
            "x" = self$terminal_reason %||%
              "A subprocess or protocol failure occurred."
          ),
          class = "dsprrr_interpreter_terminal_error"
        )
      }
      invisible(NULL)
    },

    validate_persistent_context = function(context) {
      context_names <- names(context)
      valid_names <- length(context) == 0L ||
        (!is.null(context_names) &&
          !anyNA(context_names) &&
          all(nzchar(context_names)) &&
          !anyDuplicated(context_names))
      if (!is.list(context) || is.data.frame(context) || !valid_names) {
        cli::cli_abort(
          "{.arg context} must be a uniquely named list",
          class = "dsprrr_r_code_runner_context_error"
        )
      }
      invisible(context)
    },

    timeout_ms = function() {
      if (
        !is.numeric(self$timeout) ||
          length(self$timeout) != 1L ||
          is.na(self$timeout) ||
          !is.finite(self$timeout) ||
          self$timeout <= 0
      ) {
        cli::cli_abort(
          "{.arg timeout} must be one positive finite number"
        )
      }
      as.integer(min(
        .Machine$integer.max,
        max(1, ceiling(self$timeout * 1000))
      ))
    },

    session_is_alive = function() {
      !is.null(private$session) &&
        isTRUE(tryCatch(
          private$session$is_alive(),
          error = function(e) FALSE
        ))
    },

    close_persistent_session = function(force = FALSE) {
      session <- private$session
      private$session <- NULL
      if (is.null(session)) {
        return(invisible(NULL))
      }

      close_condition <- NULL
      if (isTRUE(force)) {
        try(session$kill(grace = 0), silent = TRUE)
        try(session$wait(1000), silent = TRUE)
      } else {
        close_condition <- tryCatch(
          {
            session$close()
            NULL
          },
          interrupt = function(condition) condition,
          error = function(e) {
            e
          }
        )
        if (inherits(close_condition, "condition")) {
          try(session$kill(grace = 0), silent = TRUE)
          try(session$wait(1000), silent = TRUE)
        }
      }
      try(session$cleanup(), silent = TRUE)
      if (inherits(close_condition, "interrupt")) {
        stop(close_condition)
      }
      invisible(NULL)
    },

    terminalize_persistent = function(reason) {
      private$mark_terminal(reason)
      private$close_persistent_session(force = TRUE)
      invisible(NULL)
    },

    condition_message = function(condition) {
      if (inherits(condition, "condition")) {
        return(conditionMessage(condition))
      }
      value <- paste(as.character(condition), collapse = "\n")
      if (nzchar(value)) value else "Unknown persistent R session failure"
    },

    session_call = function(func, args = list()) {
      private$timeout_ms()
      started_at <- proc.time()[["elapsed"]]
      outcome <- tryCatch(
        {
          if (!private$session_is_alive()) {
            stop("The persistent R subprocess is not running", call. = FALSE)
          }
          private$session$call(func = func, args = args)

          answer <- NULL
          repeat {
            elapsed <- proc.time()[["elapsed"]] - started_at
            remaining <- self$timeout - elapsed
            if (remaining <= 0) {
              answer <- list(
                ok = FALSE,
                error = paste0(
                  "Execution timed out after ",
                  self$timeout,
                  " seconds"
                )
              )
              break
            }

            poll_timeout <- as.integer(min(
              .Machine$integer.max,
              max(1, ceiling(remaining * 1000))
            ))
            poll_status <- private$session$poll_process(poll_timeout)
            if (identical(poll_status, "timeout")) {
              answer <- list(
                ok = FALSE,
                error = paste0(
                  "Execution timed out after ",
                  self$timeout,
                  " seconds"
                )
              )
              break
            }

            response <- private$session$read()
            if (is.null(response)) {
              next
            }
            response_code <- as.integer(response$code %||% 0L)
            if (identical(response_code, 200L)) {
              if (!is.null(response$error)) {
                answer <- list(
                  ok = FALSE,
                  error = private$condition_message(response$error)
                )
              } else {
                answer <- list(ok = TRUE, result = response$result)
              }
              break
            }
            if (response_code >= 500L) {
              answer <- list(
                ok = FALSE,
                error = private$condition_message(
                  response$error %||% response$message
                )
              )
              break
            }
          }
          answer
        },
        interrupt = function(condition) {
          private$terminalize_persistent(
            "Persistent R execution was interrupted"
          )
          stop(condition)
        },
        error = function(condition) {
          list(ok = FALSE, error = conditionMessage(condition))
        }
      )

      if (!isTRUE(outcome$ok)) {
        private$terminalize_persistent(outcome$error)
      }
      outcome
    },

    start_persistent_session = function() {
      startup <- tryCatch(
        {
          wait_timeout <- private$timeout_ms()
          private$session <- callr::r_session$new(
            options = callr::r_session_options(
              user_profile = FALSE,
              system_profile = FALSE,
              env = c(
                callr::rcmd_safe_env(),
                "R_BROWSER" = "false",
                "R_PDFVIEWER" = "false"
              )
            ),
            wait_timeout = wait_timeout
          )
          private$session_call(
            utils::removeSource(private$persistent_initialize),
            args = list(
              prelude = self$prelude,
              allowed_packages = self$allowed_packages
            )
          )
        },
        interrupt = function(condition) {
          private$terminalize_persistent("Persistent R startup was interrupted")
          stop(condition)
        },
        error = function(condition) {
          list(ok = FALSE, error = conditionMessage(condition))
        }
      )
      if (!isTRUE(startup$ok)) {
        private$terminalize_persistent(startup$error)
      }
      startup
    },

    execute_persistent = function(code, context, start_time) {
      private$validate_persistent_context(context)

      stdout_file <- tempfile("stdout_", fileext = ".txt")
      stderr_file <- tempfile("stderr_", fileext = ".txt")
      on.exit(unlink(c(stdout_file, stderr_file)), add = TRUE)

      outcome <- private$session_call(
        utils::removeSource(private$persistent_execution_wrapper),
        args = list(
          code = code,
          context = context,
          stdout_path = stdout_file,
          stderr_path = stderr_file
        )
      )
      duration_ms <- as.numeric(
        difftime(Sys.time(), start_time, units = "secs")
      ) *
        1000
      stdout_content <- private$read_output_file(stdout_file)
      stderr_content <- private$read_output_file(stderr_file)

      if (!isTRUE(outcome$ok)) {
        return(private$error_result(
          error = outcome$error,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms,
          error_type = "interpreter"
        ))
      }

      exec_result <- outcome$result
      if (
        !is.list(exec_result) ||
          !is.logical(exec_result$success) ||
          length(exec_result$success) != 1L ||
          is.na(exec_result$success)
      ) {
        reason <- paste(
          "The persistent R subprocess returned no valid structured execution result"
        )
        private$terminalize_persistent(reason)
        return(private$error_result(
          error = reason,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms,
          error_type = "interpreter"
        ))
      }

      combine_output <- function(primary, fallback) {
        values <- c(primary %||% "", fallback %||% "")
        values <- values[nzchar(values)]
        if (length(values) == 0L) "" else paste(values, collapse = "\n")
      }
      list(
        success = exec_result$success,
        result = exec_result$result,
        stdout = private$truncate_output(combine_output(
          exec_result$stdout,
          stdout_content
        )),
        stderr = private$truncate_output(combine_output(
          exec_result$stderr,
          stderr_content
        )),
        messages = private$truncate_output(exec_result$messages %||% ""),
        warnings = private$truncate_output(exec_result$warnings %||% ""),
        error = exec_result$error,
        error_type = if (isTRUE(exec_result$success)) NULL else "execution",
        retryable = !isTRUE(exec_result$success),
        duration_ms = round(duration_ms, 2)
      )
    },

    persistent_initialize = function(prelude, allowed_packages) {
      make_exec_env <- function() {
        exec_env <- new.env(parent = globalenv())
        exec_env$.context <- list()
        exec_env$library <- function(package, ...) {
          pkg_expr <- substitute(package)
          pkg_name <- if (is.character(pkg_expr)) {
            pkg_expr
          } else {
            as.character(pkg_expr)
          }
          if (!pkg_name %in% allowed_packages) {
            stop(
              "Package '",
              pkg_name,
              "' is not in allowed_packages. ",
              "Allowed: ",
              paste(allowed_packages, collapse = ", "),
              call. = FALSE
            )
          }
          base::library(pkg_name, character.only = TRUE, ...)
        }
        exec_env$require <- function(package, ...) {
          pkg_expr <- substitute(package)
          pkg_name <- if (is.character(pkg_expr)) {
            pkg_expr
          } else {
            as.character(pkg_expr)
          }
          if (!pkg_name %in% allowed_packages) {
            stop(
              "Package '",
              pkg_name,
              "' is not in allowed_packages. ",
              "Allowed: ",
              paste(allowed_packages, collapse = ", "),
              call. = FALSE
            )
          }
          base::require(pkg_name, character.only = TRUE, ...)
        }
        if (length(prelude) > 0L) {
          for (statement in prelude) {
            base::eval(base::parse(text = statement), envir = exec_env)
          }
        }
        exec_env
      }

      state <- new.env(parent = emptyenv())
      state$base_context <- list()
      state$make_exec_env <- make_exec_env
      state$exec_env <- make_exec_env()
      # This function runs inside an owned callr session. Keep the persistent
      # interpreter state in that child session's global environment without
      # exposing a package-process global assignment to static checkers.
      session_env <- globalenv()
      session_env$.dsprrr_r_code_runner_state <- state
      TRUE
    },

    persistent_prepare_context = function(context) {
      state <- get(
        ".dsprrr_r_code_runner_state",
        envir = globalenv(),
        inherits = FALSE
      )
      state$base_context <- context
      state$exec_env$.context <- context
      TRUE
    },

    persistent_reset = function() {
      state <- get(
        ".dsprrr_r_code_runner_state",
        envir = globalenv(),
        inherits = FALSE
      )
      state$base_context <- list()
      state$exec_env <- state$make_exec_env()
      TRUE
    },

    persistent_execution_wrapper = function(
      code,
      context,
      stdout_path,
      stderr_path
    ) {
      state <- get(
        ".dsprrr_r_code_runner_state",
        envir = globalenv(),
        inherits = FALSE
      )
      effective_context <- state$base_context
      if (length(context) > 0L) {
        for (name in names(context)) {
          effective_context[name] <- context[name]
        }
      }
      state$exec_env$.context <- effective_context

      messages <- character()
      warnings <- character()
      stdout_connection <- file(stdout_path, open = "wt")
      stderr_connection <- file(stderr_path, open = "wt")
      output_sinks <- sink.number(type = "output")
      message_sink <- sink.number(type = "message")
      sink(stdout_connection, type = "output")
      sink(stderr_connection, type = "message")
      restore_sinks <- function() {
        while (sink.number(type = "message") != message_sink) {
          sink(type = "message")
        }
        while (sink.number(type = "output") > output_sinks) {
          sink(type = "output")
        }
        close(stdout_connection)
        close(stderr_connection)
        invisible(NULL)
      }
      on.exit(restore_sinks(), add = TRUE)

      result <- tryCatch(
        {
          withCallingHandlers(
            base::eval(
              base::parse(text = code),
              envir = state$exec_env
            ),
            message = function(message) {
              messages <<- c(messages, conditionMessage(message))
              invokeRestart("muffleMessage")
            },
            warning = function(warning) {
              warnings <<- c(warnings, conditionMessage(warning))
              invokeRestart("muffleWarning")
            }
          )
        },
        error = function(error) {
          structure(
            list(msg = conditionMessage(error)),
            class = "code_error"
          )
        }
      )
      restore_sinks()
      on.exit(NULL, add = FALSE)

      if (inherits(result, "code_error")) {
        list(
          success = FALSE,
          result = NULL,
          stdout = "",
          stderr = "",
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = result$msg
        )
      } else {
        list(
          success = TRUE,
          result = result,
          stdout = "",
          stderr = "",
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = NULL
        )
      }
    },

    #' Wrapper function that runs inside the subprocess
    #' NOTE: Intentionally uses eval() - this is the core purpose of
    #' ProgramOfThought/CodeAct modules (execute LLM-generated code)
    execution_wrapper = function(
      code,
      context,
      prelude,
      allowed_packages,
      stdout_path,
      stderr_path
    ) {
      # Capture messages and warnings
      messages <- character()
      warnings <- character()
      stdout_connection <- file(stdout_path, open = "wt")
      stderr_connection <- file(stderr_path, open = "wt")
      output_sinks <- sink.number(type = "output")
      message_sink <- sink.number(type = "message")
      sink(stdout_connection, type = "output")
      sink(stderr_connection, type = "message")
      restore_sinks <- function() {
        while (sink.number(type = "message") != message_sink) {
          sink(type = "message")
        }
        while (sink.number(type = "output") > output_sinks) {
          sink(type = "output")
        }
        close(stdout_connection)
        close(stderr_connection)
        invisible(NULL)
      }
      on.exit(restore_sinks(), add = TRUE)

      result <- tryCatch(
        {
          # Set up message/warning handlers
          withCallingHandlers(
            {
              # Make context available
              .context <- context

              # Create execution environment with context
              exec_env <- new.env(parent = globalenv())
              exec_env$.context <- context

              # Override library/require to enforce allowed_packages
              exec_env$library <- function(package, ...) {
                pkg_expr <- substitute(package)
                pkg_name <- if (is.character(pkg_expr)) {
                  pkg_expr
                } else {
                  as.character(pkg_expr)
                }
                if (!pkg_name %in% allowed_packages) {
                  stop(
                    "Package '",
                    pkg_name,
                    "' is not in allowed_packages. ",
                    "Allowed: ",
                    paste(allowed_packages, collapse = ", "),
                    call. = FALSE
                  )
                }
                base::library(pkg_name, character.only = TRUE, ...)
              }

              exec_env$require <- function(package, ...) {
                pkg_expr <- substitute(package)
                pkg_name <- if (is.character(pkg_expr)) {
                  pkg_expr
                } else {
                  as.character(pkg_expr)
                }
                if (!pkg_name %in% allowed_packages) {
                  stop(
                    "Package '",
                    pkg_name,
                    "' is not in allowed_packages. ",
                    "Allowed: ",
                    paste(allowed_packages, collapse = ", "),
                    call. = FALSE
                  )
                }
                base::require(pkg_name, character.only = TRUE, ...)
              }

              # Run prelude if any
              if (length(prelude) > 0) {
                for (p in prelude) {
                  base::eval(base::parse(text = p), envir = exec_env)
                }
              }

              # Evaluate the user code - this is intentional for code execution
              # Operational safeguards are subprocess isolation, timeout, and
              # pattern checks. They are not a security boundary.
              base::eval(base::parse(text = code), envir = exec_env)
            },
            message = function(m) {
              messages <<- c(messages, conditionMessage(m))
              invokeRestart("muffleMessage")
            },
            warning = function(w) {
              warnings <<- c(warnings, conditionMessage(w))
              invokeRestart("muffleWarning")
            }
          )
        },
        error = function(e) {
          structure(
            list(msg = conditionMessage(e)),
            class = "code_error"
          )
        }
      )
      restore_sinks()
      on.exit(NULL, add = FALSE)

      if (inherits(result, "code_error")) {
        list(
          success = FALSE,
          result = NULL,
          stdout = "",
          stderr = "",
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = result$msg
        )
      } else {
        list(
          success = TRUE,
          result = result,
          stdout = "",
          stderr = "",
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = NULL
        )
      }
    },

    #' Check for dangerous code patterns (defense in depth)
    check_dangerous_patterns = function(code) {
      # Note: This is NOT a security boundary, just defense in depth
      # Real security requires OS-level sandboxing

      dangerous_patterns <- list(
        # System access (including base:: prefix bypass attempts)
        "(?:base::)?system\\s*\\(" = "system() calls are not allowed",
        "(?:base::)?system2\\s*\\(" = "system2() calls are not allowed",
        "(?:base::)?Sys\\.setenv" = "Modifying environment variables is not allowed",

        # do.call bypass attempts
        "do\\.call\\s*\\(\\s*['\"]?system" = "do.call(system) is not allowed",
        "do\\.call\\s*\\(\\s*['\"]?system2" = "do.call(system2) is not allowed",

        # File system (destructive operations)
        "(?:base::)?unlink\\s*\\(" = "unlink() is not allowed",
        "(?:base::)?file\\.remove" = "file.remove() is not allowed",

        # Process control
        "(?:base::)?quit\\s*\\(" = "quit() is not allowed",
        "(?:base::)?q\\s*\\(\\s*\\)" = "q() is not allowed",

        # Network (basic check)
        "(?:utils::)?download\\.file" = "download.file() is not allowed",
        "(?:base::)?url\\s*\\(" = "url() connections are not allowed"
      )

      for (pattern in names(dangerous_patterns)) {
        if (grepl(pattern, code, ignore.case = FALSE, perl = TRUE)) {
          return(paste0(
            "Dangerous pattern detected: ",
            dangerous_patterns[[pattern]]
          ))
        }
      }

      NULL
    },

    #' Read and handle output file
    read_output_file = function(filepath) {
      if (file.exists(filepath)) {
        tryCatch(
          {
            connection <- file(filepath, open = "rb")
            on.exit(close(connection), add = TRUE)
            read_limit <- min(
              as.double(self$max_output_chars) + 1,
              .Machine$integer.max
            )
            output <- readChar(
              connection,
              nchars = read_limit,
              useBytes = FALSE
            )
            if (length(output) == 0L) {
              return("")
            }
            sub("\\r?\\n$", "", output, perl = TRUE)
          },
          error = function(e) {
            cli::cli_warn(c(
              "Failed to read subprocess output",
              "x" = "Error: {e$message}"
            ))
            "[OUTPUT CAPTURE FAILED]"
          }
        )
      } else {
        ""
      }
    },

    #' Truncate output to max size
    truncate_output = function(text) {
      if (nchar(text) > self$max_output_chars) {
        paste0(
          substr(text, 1, self$max_output_chars),
          "\n... [TRUNCATED - exceeded ",
          self$max_output_chars,
          " characters]"
        )
      } else {
        text
      }
    },

    #' Create an error result structure
    error_result = function(
      error,
      stdout = "",
      stderr = "",
      messages = "",
      warnings = "",
      duration_ms = 0,
      error_type = "execution"
    ) {
      list(
        success = FALSE,
        result = NULL,
        stdout = private$truncate_output(stdout),
        stderr = private$truncate_output(stderr),
        messages = messages,
        warnings = warnings,
        error = error,
        error_type = error_type,
        retryable = identical(error_type, "execution"),
        duration_ms = round(duration_ms, 2)
      )
    },

    mark_terminal = function(reason) {
      self$terminal <- TRUE
      self$terminal_reason <- as.character(reason)[[1L]]
      invisible(NULL)
    },

    finalize = function() {
      # Do not call processx/callr methods from an R garbage-collection
      # finalizer. Native process setup may be active for another session, and
      # re-entering processx teardown from GC can crash the host R process.
      # Invocation-owned runners are closed by with_code_runner_lease(); callers
      # that retain a runner own its explicit close(). The callr session's own
      # processx finalizer remains responsible for abandoned resources.
      invisible(NULL)
    }
  )
)
