#' R Code Execution Backend
#'
#' @description
#' A subprocess execution backend for running R code generated by LLMs. Uses
#' callr for process isolation, timeout protection, output capture, and
#' structured result handling.
#'
#' @details
#' RCodeRunner provides:
#' - **Process isolation**: Code runs in a separate R process via callr
#' - **Timeout protection**: Configurable timeout prevents runaway execution
#' - **Output capture**: Captures stdout, stderr, messages, and warnings
#' - **Context passing**: Inject data into the execution environment
#' - **Output limiting**: Truncates large outputs to prevent memory issues
#'
#' Security note: `r_code_runner()` is a **trusted-input-only** backend. callr
#' starts a separate process, but that process retains the host user's file,
#' network, environment, and operating-system permissions. Pattern checks are
#' only defense in depth and can be bypassed. For untrusted inputs, provide a
#' runner backed by a container or OS-level sandbox.
#'
#' Code-executing modules accept any runner that implements the dsprrr runner
#' protocol. A runner must expose `execute(code, context = list())` and
#' `policy()` methods. `policy()` returns a uniquely named list containing at
#' least `backend` (character), `trust` (character), and `sandboxed` (logical).
#' `execute()` returns one uniquely named list. `success` and `result` are
#' required. Missing `stdout`, `stderr`, `messages`, and `warnings` fields are
#' normalized to empty strings, and missing `duration_ms` is normalized to
#' `NA`. A failed result must include a non-empty `error`; a successful result
#' may omit it.
#'
#' Code-executing modules accept exactly one runtime source. Passing `runner`
#' retains that caller-owned object and never closes it. Passing a zero-argument
#' `interpreter_factory` creates one fresh invocation-owned runner; factory
#' results must also implement idempotent terminal `close()`, which dsprrr calls
#' exactly once on success, error, or interrupt.
#'
#' @examples
#' \dontrun{
#' runner <- r_code_runner(timeout = 5)
#'
#' # Simple execution
#' result <- runner$execute("1 + 1")
#' result$result
#' # [1] 2
#'
#' # With context
#' result <- runner$execute(
#'   "mean(.context$data$mpg)",
#'   context = list(data = mtcars)
#' )
#' result$result
#' # [1] 20.09062
#'
#' # Timeout handling
#' result <- runner$execute("Sys.sleep(100)")
#' result$success
#' # [1] FALSE
#' result$error
#' # "Execution timed out after 5 seconds"
#' }
#'
#' @name r-code-runner
NULL

#' Create an R Code Runner
#'
#' @description
#' Factory function to create a trusted-input-only RCodeRunner instance.
#'
#' @param timeout Numeric. Maximum execution time in seconds. Default 30.
#' @param max_output_chars Integer. Maximum characters for stdout/stderr.
#'   Output exceeding this limit is truncated. Default 100000 (100KB).
#' @param allowed_packages Character vector. Packages that may be loaded.
#'   This is defense-in-depth only; not a security boundary.
#'
#'   Default: c("base", "stats", "utils", "methods").
#' @param prelude Character vector. R code to run before user code.
#'   Useful for setting options or loading common utilities.
#'
#' @return An RCodeRunner R6 object
#'
#' @export
#' @examples
#' \dontrun{
#' runner <- r_code_runner(timeout = 10)
#' result <- runner$execute("sqrt(16)")
#' result$result
#' # [1] 4
#' }
r_code_runner <- function(
  timeout = 30,
  max_output_chars = 100000L,
  allowed_packages = c("base", "stats", "utils", "methods"),
  prelude = character()
) {
  rlang::check_installed("callr", reason = "for code execution")

  RCodeRunner$new(
    timeout = timeout,
    max_output_chars = as.integer(max_output_chars),
    allowed_packages = allowed_packages,
    prelude = prelude
  )
}


# Validate the structural runner protocol used by code-executing modules.
validate_code_runner <- function(runner) {
  execute <- tryCatch(runner[["execute"]], error = function(e) NULL)
  policy <- tryCatch(runner[["policy"]], error = function(e) NULL)

  if (!is.function(execute) || !is.function(policy)) {
    cli::cli_abort(
      c(
        "runner must implement the dsprrr code-runner protocol",
        "x" = "A runner needs {.code execute(code, context)} and {.code policy()} methods.",
        "i" = "Use {.code r_code_runner()} for trusted inputs or provide a sandboxed backend."
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  runner_policy <- tryCatch(
    policy(),
    error = function(e) {
      cli::cli_abort(
        c(
          "runner$policy() failed",
          "x" = conditionMessage(e)
        ),
        class = "dsprrr_code_runner_protocol_error"
      )
    }
  )
  policy_names <- names(runner_policy)
  required <- c("backend", "trust", "sandboxed")
  missing_fields <- setdiff(required, policy_names)

  valid_names <- is.list(runner_policy) &&
    !is.null(policy_names) &&
    !anyNA(policy_names) &&
    all(nzchar(policy_names)) &&
    !anyDuplicated(policy_names)
  if (!valid_names || length(missing_fields) > 0) {
    cli::cli_abort(
      c(
        "runner$policy() must return a uniquely named list",
        "x" = "Missing required fields: {.field {missing_fields}}",
        "i" = "Required fields are {.field backend}, {.field trust}, and {.field sandboxed}."
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  valid_backend <- is.character(runner_policy$backend) &&
    length(runner_policy$backend) == 1L &&
    !is.na(runner_policy$backend) &&
    nzchar(runner_policy$backend)
  valid_trust <- is.character(runner_policy$trust) &&
    length(runner_policy$trust) == 1L &&
    !is.na(runner_policy$trust) &&
    nzchar(runner_policy$trust)
  valid_sandboxed <- is.logical(runner_policy$sandboxed) &&
    length(runner_policy$sandboxed) == 1L &&
    !is.na(runner_policy$sandboxed)

  if (!valid_backend || !valid_trust || !valid_sandboxed) {
    cli::cli_abort(
      c(
        "runner$policy() returned invalid metadata",
        "i" = "{.field backend} and {.field trust} must be non-empty strings.",
        "i" = "{.field sandboxed} must be TRUE or FALSE."
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  invisible(runner_policy)
}


summarize_code_runner_policy <- function(policy) {
  list(
    backend = policy$backend,
    trust = policy$trust,
    sandboxed = policy$sandboxed,
    persistent = if (
      is.logical(policy$persistent) &&
        length(policy$persistent) == 1L &&
        !is.na(policy$persistent)
    ) {
      policy$persistent
    } else {
      NA
    }
  )
}


validate_code_runner_result <- function(result) {
  result_names <- names(result)
  if (
    !is.list(result) ||
      is.null(result_names) ||
      anyNA(result_names) ||
      any(!nzchar(result_names)) ||
      anyDuplicated(result_names)
  ) {
    cli::cli_abort(
      "runner$execute() must return one named result list",
      class = "dsprrr_code_runner_protocol_error"
    )
  }
  required <- c("success", "result")
  missing <- setdiff(required, names(result))
  if (length(missing) > 0L) {
    cli::cli_abort(
      c(
        "runner$execute() returned an incomplete result",
        "x" = "Missing field{?s}: {.field {missing}}"
      ),
      class = "dsprrr_code_runner_protocol_error"
    )
  }
  if (
    !is.logical(result$success) ||
      length(result$success) != 1L ||
      is.na(result$success)
  ) {
    cli::cli_abort(
      "runner$execute() field {.field success} must be TRUE or FALSE",
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  normalize_text <- function(name) {
    value <- result[[name]]
    if (is.null(value)) {
      return("")
    }
    if (!is.character(value) || length(value) != 1L || is.na(value)) {
      cli::cli_abort(
        "runner$execute() field {.field {name}} must be one non-missing string",
        class = "dsprrr_code_runner_protocol_error"
      )
    }
    value
  }
  for (name in c("stdout", "stderr", "messages", "warnings")) {
    result[[name]] <- normalize_text(name)
  }

  error <- result$error
  if (isTRUE(result$success)) {
    if (
      !is.null(error) &&
        (!is.character(error) ||
          length(error) != 1L ||
          is.na(error))
    ) {
      cli::cli_abort(
        "runner$execute() field {.field error} must be NULL or one string",
        class = "dsprrr_code_runner_protocol_error"
      )
    }
  } else if (
    !is.character(error) ||
      length(error) != 1L ||
      is.na(error) ||
      !nzchar(error)
  ) {
    cli::cli_abort(
      "A failed runner result must contain one non-empty {.field error}",
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  duration <- result$duration_ms
  if (is.null(duration)) {
    result$duration_ms <- NA_real_
  } else if (
    !is.numeric(duration) ||
      length(duration) != 1L ||
      (!is.na(duration) && (!is.finite(duration) || duration < 0))
  ) {
    cli::cli_abort(
      "runner$execute() field {.field duration_ms} must be one non-negative number or NA",
      class = "dsprrr_code_runner_protocol_error"
    )
  }

  result$error <- error %||% NULL
  result
}


execute_code_runner <- function(
  runner,
  code,
  context = list(),
  .control_nonce = NULL
) {
  execute_args <- list(code = code, context = context)
  execute_formals <- tryCatch(
    names(formals(runner$execute)),
    error = function(e) character()
  )
  accepts_dots <- "..." %in% execute_formals
  if (
    !is.null(.control_nonce) &&
      (".control_nonce" %in% execute_formals || accepts_dots)
  ) {
    execute_args$.control_nonce <- .control_nonce
  }
  result <- do.call(runner$execute, execute_args)
  validate_code_runner_result(result)
}


# Validate the zero-argument factory contract used by code-executing modules.
# The factory is deliberately not invoked during module construction: creating
# an interpreter may start a process or open a network connection.
validate_interpreter_factory <- function(interpreter_factory) {
  if (!is.function(interpreter_factory)) {
    cli::cli_abort(
      "{.arg interpreter_factory} must be a zero-argument function",
      class = "dsprrr_interpreter_factory_error"
    )
  }

  if (is.primitive(interpreter_factory)) {
    cli::cli_abort(
      "{.arg interpreter_factory} must have an inspectable zero-argument signature",
      class = "dsprrr_interpreter_factory_error"
    )
  }

  factory_formals <- tryCatch(
    formals(interpreter_factory),
    error = function(e) NULL
  )

  required <- names(factory_formals)[vapply(
    factory_formals,
    identical,
    logical(1),
    quote(expr = )
  )]
  required <- setdiff(required, "...")
  if (length(required) > 0L) {
    cli::cli_abort(
      c(
        "{.arg interpreter_factory} must be callable without arguments",
        "x" = "Required argument{?s}: {.arg {required}}"
      ),
      class = "dsprrr_interpreter_factory_error"
    )
  }

  invisible(interpreter_factory)
}


validate_interpreter_close <- function(close) {
  if (!is.function(close)) {
    cli::cli_abort(
      c(
        "{.arg interpreter_factory} returned a runner without {.code close()}",
        "i" = "Invocation-owned runners must implement {.code execute()}, {.code policy()}, and {.code close()}."
      ),
      class = "dsprrr_interpreter_factory_error"
    )
  }
  if (is.primitive(close)) {
    cli::cli_abort(
      "A factory-created runner's {.code close()} must have an inspectable zero-argument signature",
      class = "dsprrr_interpreter_factory_error"
    )
  }

  close_formals <- tryCatch(formals(close), error = function(e) NULL)
  required <- names(close_formals)[vapply(
    close_formals,
    identical,
    logical(1),
    quote(expr = )
  )]
  required <- setdiff(required, "...")
  if (length(required) > 0L) {
    cli::cli_abort(
      c(
        "A factory-created runner's {.code close()} must be callable without arguments",
        "x" = "Required argument{?s}: {.arg {required}}",
        "i" = "The module will not execute with a runner whose cleanup contract is invalid."
      ),
      class = "dsprrr_interpreter_factory_error"
    )
  }

  invisible(close)
}


# Normalize a constructor's mutually exclusive runtime choices without opening
# a factory-created interpreter.
normalize_code_runner_binding <- function(
  runner = NULL,
  interpreter_factory = NULL,
  module_name = "Code execution"
) {
  if (is.null(runner) && is.null(interpreter_factory)) {
    cli::cli_abort(
      c(
        "{module_name} requires an explicit runner or interpreter_factory",
        "i" = "Use {.code runner = r_code_runner()} for a caller-owned runner.",
        "i" = "Use {.code interpreter_factory = r_code_runner} for a fresh runner per invocation."
      ),
      class = "dsprrr_interpreter_binding_error"
    )
  }
  if (!is.null(runner) && !is.null(interpreter_factory)) {
    cli::cli_abort(
      "Supply only one of {.arg runner} and {.arg interpreter_factory}",
      class = "dsprrr_interpreter_binding_error"
    )
  }

  if (!is.null(runner)) {
    validate_code_runner(runner)
    return(list(
      runner = runner,
      interpreter_factory = NULL,
      lifecycle = "caller-owned"
    ))
  }

  validate_interpreter_factory(interpreter_factory)
  list(
    runner = NULL,
    interpreter_factory = interpreter_factory,
    lifecycle = "invocation-owned"
  )
}


# Acquire one runtime interpreter. Factory-created runners must expose close()
# because the module, rather than the caller, owns their lifecycle.
acquire_code_runner <- function(runner, interpreter_factory, module_name) {
  if (is.null(runner) == is.null(interpreter_factory)) {
    cli::cli_abort(
      "{module_name} must have exactly one of {.arg runner} and {.arg interpreter_factory}",
      class = "dsprrr_interpreter_binding_error"
    )
  }
  if (!is.null(runner)) {
    runner_policy <- validate_code_runner(runner)
    return(list(
      runner = runner,
      owned = FALSE,
      policy = runner_policy,
      policy_summary = summarize_code_runner_policy(runner_policy),
      module_name = module_name
    ))
  }

  validate_interpreter_factory(interpreter_factory)
  created <- tryCatch(
    interpreter_factory(),
    error = function(e) {
      cli::cli_abort(
        "{module_name} could not create an interpreter",
        parent = e,
        class = "dsprrr_interpreter_factory_error"
      )
    }
  )
  validation <- tryCatch(
    validate_code_runner(created),
    interrupt = function(e) e,
    error = function(e) e
  )
  if (inherits(validation, "condition")) {
    close <- tryCatch(created[["close"]], error = function(e) NULL)
    close_error <- if (is.function(close)) {
      tryCatch(
        {
          close()
          NULL
        },
        interrupt = function(e) e,
        error = function(e) e
      )
    } else {
      NULL
    }
    if (inherits(close_error, "condition")) {
      attr(validation, "dsprrr_interpreter_close_error") <- close_error
    }
    if (inherits(validation, "interrupt")) {
      stop(validation)
    }
    cli::cli_abort(
      "{.arg interpreter_factory} returned an invalid runner",
      parent = validation,
      class = "dsprrr_interpreter_factory_error"
    )
  }
  runner_policy <- validation
  close <- tryCatch(created[["close"]], error = function(e) NULL)
  validate_interpreter_close(close)

  list(
    runner = created,
    owned = TRUE,
    policy = runner_policy,
    policy_summary = summarize_code_runner_policy(runner_policy),
    module_name = module_name
  )
}


# Close one invocation-owned runner and return, rather than signal, any error.
close_code_runner_lease <- function(lease) {
  if (!is.list(lease) || !isTRUE(lease$owned)) {
    return(NULL)
  }
  tryCatch(
    {
      lease$runner$close()
      NULL
    },
    interrupt = function(e) e,
    error = function(e) e
  )
}


# Run a module body under one interpreter lease. Cleanup after a successful
# body is part of success and therefore errors if it fails. When execution and
# cleanup both fail, the execution condition remains primary and carries the
# cleanup condition as diagnostic metadata.
with_code_runner_lease <- function(
  runner,
  interpreter_factory,
  module_name,
  code
) {
  if (!is.function(code)) {
    cli::cli_abort("Internal interpreter lease body must be a function")
  }
  lease <- acquire_code_runner(runner, interpreter_factory, module_name)
  outcome <- tryCatch(
    list(ok = TRUE, value = code(lease$runner, lease)),
    interrupt = function(condition) list(ok = FALSE, condition = condition),
    error = function(condition) list(ok = FALSE, condition = condition)
  )
  close_error <- close_code_runner_lease(lease)

  if (!isTRUE(outcome$ok)) {
    if (inherits(close_error, "condition")) {
      attr(outcome$condition, "dsprrr_interpreter_close_error") <- close_error
    }
    stop(outcome$condition)
  }
  if (inherits(close_error, "condition")) {
    cli::cli_abort(
      "{module_name} could not close its invocation-owned interpreter",
      parent = close_error,
      class = "dsprrr_interpreter_close_error"
    )
  }

  outcome$value
}


code_runner_binding_label <- function(runner, interpreter_factory) {
  if (!is.null(interpreter_factory)) {
    return("fresh runner per invocation")
  }
  policy <- tryCatch(runner$policy(), error = function(e) list())
  paste0(policy$backend %||% class(runner)[1L], " (caller-owned)")
}


#' RCodeRunner R6 Class
#'
#' @description
#' R6 class for trusted R code execution in separate subprocesses.
#'
#' TRUST NOTE: This class intentionally uses eval() to execute
#' LLM-generated R code. This is the core purpose of the ProgramOfThought
#' and CodeAct modules. It provides operational safeguards through:
#' 1. Opt-in design (requires explicit runner creation)
#' 2. Subprocess isolation via callr
#' 3. Timeout protection
#' 4. Dangerous pattern scanning (defense in depth)
#'
#' These safeguards do not restrict host permissions and are not a security
#' boundary. For untrusted input, provide a runner backed by OS-level sandboxing.
#'
#' @keywords internal
#' @noRd
RCodeRunner <- R6::R6Class(
  "RCodeRunner",
  public = list(
    #' @field timeout Maximum execution time in seconds
    timeout = NULL,

    #' @field max_output_chars Maximum output size before truncation
    max_output_chars = NULL,

    #' @field allowed_packages Packages allowed to be loaded
    allowed_packages = NULL,

    #' @field prelude Code to run before user code
    prelude = NULL,

    #' @field closed Whether this runner has been closed
    closed = FALSE,

    #' @description
    #' Initialize a new RCodeRunner
    #' @param timeout Numeric timeout in seconds
    #' @param max_output_chars Integer max output size
    #' @param allowed_packages Character vector of allowed packages
    #' @param prelude Character vector of prelude code
    initialize = function(
      timeout = 30,
      max_output_chars = 100000L,
      allowed_packages = c("base", "stats", "utils", "methods"),
      prelude = character()
    ) {
      self$timeout <- timeout
      self$max_output_chars <- max_output_chars
      self$allowed_packages <- allowed_packages
      self$prelude <- prelude
    },

    #' @description
    #' Execute R code in an isolated subprocess
    #'
    #' @param code Character string of R code to execute
    #' @param context Named list of objects to make available as `.context`
    #'
    #' @return A list with components:
    #'   - `success`: Logical indicating successful execution
    #'   - `result`: The return value of the code (NULL on error)
    #'   - `stdout`: Character string of stdout output
    #'   - `stderr`: Character string of stderr output
    #'   - `messages`: Character string of message() output
    #'   - `warnings`: Character string of warning() output
    #'   - `error`: Error message if failed (NULL on success)
    #'   - `duration_ms`: Execution time in milliseconds
    execute = function(code, context = list()) {
      if (self$closed) {
        cli::cli_abort(
          "The R code runner is closed",
          class = "dsprrr_interpreter_closed_error"
        )
      }
      if (!is.character(code) || length(code) != 1) {
        cli::cli_abort("code must be a single character string")
      }

      start_time <- Sys.time()

      # Check for dangerous patterns (defense in depth)
      danger_check <- private$check_dangerous_patterns(code)
      if (!is.null(danger_check)) {
        return(private$error_result(
          error = danger_check,
          duration_ms = 0
        ))
      }

      # Create temp files for output capture
      stdout_file <- tempfile("stdout_", fileext = ".txt")
      stderr_file <- tempfile("stderr_", fileext = ".txt")
      on.exit(unlink(c(stdout_file, stderr_file)), add = TRUE)

      # Build the execution wrapper
      # Source metadata is not needed in the child. Removing it keeps the
      # serialized worker small and prevents coverage instrumentation from
      # making each callr process load the parent package namespace.
      worker <- utils::removeSource(private$execution_wrapper)
      exec_result <- tryCatch(
        {
          callr::r(
            func = worker,
            args = list(
              code = code,
              context = context,
              prelude = self$prelude,
              allowed_packages = self$allowed_packages
            ),
            timeout = self$timeout,
            stdout = stdout_file,
            stderr = stderr_file,
            user_profile = FALSE,
            env = c(
              callr::rcmd_safe_env(),
              "R_BROWSER" = "false",
              "R_PDFVIEWER" = "false"
            )
          )
        },
        callr_timeout_error = function(e) {
          structure(
            list(
              error = paste0(
                "Execution timed out after ",
                self$timeout,
                " seconds"
              )
            ),
            class = "timeout_error"
          )
        },
        system_command_timeout_error = function(e) {
          structure(
            list(
              error = paste0(
                "Execution timed out after ",
                self$timeout,
                " seconds"
              )
            ),
            class = "timeout_error"
          )
        },
        error = function(e) {
          structure(
            list(error = conditionMessage(e)),
            class = "exec_error"
          )
        }
      )

      duration_ms <- as.numeric(
        difftime(Sys.time(), start_time, units = "secs")
      ) *
        1000

      # Read captured output
      stdout_content <- private$read_output_file(stdout_file)
      stderr_content <- private$read_output_file(stderr_file)

      # Handle different result types
      if (inherits(exec_result, "timeout_error")) {
        return(private$error_result(
          error = exec_result$error,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms
        ))
      }

      if (inherits(exec_result, "exec_error")) {
        return(private$error_result(
          error = exec_result$error,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms
        ))
      }

      # Successful execution - exec_result is the wrapper's return value
      list(
        success = exec_result$success,
        result = exec_result$result,
        stdout = private$truncate_output(stdout_content),
        stderr = private$truncate_output(stderr_content),
        messages = private$truncate_output(exec_result$messages %||% ""),
        warnings = private$truncate_output(exec_result$warnings %||% ""),
        error = exec_result$error,
        duration_ms = round(duration_ms, 2)
      )
    },

    #' @description
    #' Describe the execution backend's trust boundary
    #'
    #' @return A named list implementing the dsprrr runner policy contract
    policy = function() {
      list(
        backend = "callr",
        trust = "trusted-input-only",
        sandboxed = FALSE,
        persistent = FALSE,
        process_isolation = TRUE,
        filesystem_access = "host-user",
        network_access = "host-user",
        pattern_scan = "defense-in-depth"
      )
    },

    #' @description
    #' Close the runner
    #'
    #' `RCodeRunner` starts one subprocess per `execute()` call, so there is no
    #' persistent session to tear down. Closing marks the object terminal and
    #' satisfies the managed interpreter lifecycle protocol.
    #'
    #' @return The runner, invisibly
    close = function() {
      self$closed <- TRUE
      invisible(self)
    },

    #' @description
    #' Print method for RCodeRunner
    print = function() {
      trust <- self$policy()$trust
      cli::cli_h3("RCodeRunner")
      cli::cli_bullets(c(
        "*" = "Timeout: {.val {self$timeout}} seconds",
        "*" = "Max output: {.val {self$max_output_chars}} chars",
        "*" = "Allowed packages: {.val {self$allowed_packages}}",
        "!" = "Trust: {.val {trust}}; not sandboxed"
      ))
      invisible(self)
    }
  ),

  private = list(
    #' Wrapper function that runs inside the subprocess
    #' NOTE: Intentionally uses eval() - this is the core purpose of
    #' ProgramOfThought/CodeAct modules (execute LLM-generated code)
    execution_wrapper = function(code, context, prelude, allowed_packages) {
      # Capture messages and warnings
      messages <- character()
      warnings <- character()

      result <- tryCatch(
        {
          # Set up message/warning handlers
          withCallingHandlers(
            {
              # Make context available
              .context <- context

              # Create execution environment with context
              exec_env <- new.env(parent = globalenv())
              exec_env$.context <- context

              # Override library/require to enforce allowed_packages
              exec_env$library <- function(package, ...) {
                pkg_expr <- substitute(package)
                pkg_name <- if (is.character(pkg_expr)) {
                  pkg_expr
                } else {
                  as.character(pkg_expr)
                }
                if (!pkg_name %in% allowed_packages) {
                  stop(
                    "Package '",
                    pkg_name,
                    "' is not in allowed_packages. ",
                    "Allowed: ",
                    paste(allowed_packages, collapse = ", "),
                    call. = FALSE
                  )
                }
                base::library(pkg_name, character.only = TRUE, ...)
              }

              exec_env$require <- function(package, ...) {
                pkg_expr <- substitute(package)
                pkg_name <- if (is.character(pkg_expr)) {
                  pkg_expr
                } else {
                  as.character(pkg_expr)
                }
                if (!pkg_name %in% allowed_packages) {
                  stop(
                    "Package '",
                    pkg_name,
                    "' is not in allowed_packages. ",
                    "Allowed: ",
                    paste(allowed_packages, collapse = ", "),
                    call. = FALSE
                  )
                }
                base::require(pkg_name, character.only = TRUE, ...)
              }

              # Run prelude if any
              if (length(prelude) > 0) {
                for (p in prelude) {
                  base::eval(base::parse(text = p), envir = exec_env)
                }
              }

              # Evaluate the user code - this is intentional for code execution
              # Operational safeguards are subprocess isolation, timeout, and
              # pattern checks. They are not a security boundary.
              base::eval(base::parse(text = code), envir = exec_env)
            },
            message = function(m) {
              messages <<- c(messages, conditionMessage(m))
              invokeRestart("muffleMessage")
            },
            warning = function(w) {
              warnings <<- c(warnings, conditionMessage(w))
              invokeRestart("muffleWarning")
            }
          )
        },
        error = function(e) {
          structure(
            list(msg = conditionMessage(e)),
            class = "code_error"
          )
        }
      )

      if (inherits(result, "code_error")) {
        list(
          success = FALSE,
          result = NULL,
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = result$msg
        )
      } else {
        list(
          success = TRUE,
          result = result,
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = NULL
        )
      }
    },

    #' Check for dangerous code patterns (defense in depth)
    check_dangerous_patterns = function(code) {
      # Note: This is NOT a security boundary, just defense in depth
      # Real security requires OS-level sandboxing

      dangerous_patterns <- list(
        # System access (including base:: prefix bypass attempts)
        "(?:base::)?system\\s*\\(" = "system() calls are not allowed",
        "(?:base::)?system2\\s*\\(" = "system2() calls are not allowed",
        "(?:base::)?Sys\\.setenv" = "Modifying environment variables is not allowed",

        # do.call bypass attempts
        "do\\.call\\s*\\(\\s*['\"]?system" = "do.call(system) is not allowed",
        "do\\.call\\s*\\(\\s*['\"]?system2" = "do.call(system2) is not allowed",

        # File system (destructive operations)
        "(?:base::)?unlink\\s*\\(" = "unlink() is not allowed",
        "(?:base::)?file\\.remove" = "file.remove() is not allowed",

        # Process control
        "(?:base::)?quit\\s*\\(" = "quit() is not allowed",
        "(?:base::)?q\\s*\\(\\s*\\)" = "q() is not allowed",

        # Network (basic check)
        "(?:utils::)?download\\.file" = "download.file() is not allowed",
        "(?:base::)?url\\s*\\(" = "url() connections are not allowed"
      )

      for (pattern in names(dangerous_patterns)) {
        if (grepl(pattern, code, ignore.case = FALSE, perl = TRUE)) {
          return(paste0(
            "Dangerous pattern detected: ",
            dangerous_patterns[[pattern]]
          ))
        }
      }

      NULL
    },

    #' Read and handle output file
    read_output_file = function(filepath) {
      if (file.exists(filepath)) {
        tryCatch(
          paste(readLines(filepath, warn = FALSE), collapse = "\n"),
          error = function(e) {
            cli::cli_warn(c(
              "Failed to read subprocess output",
              "x" = "Error: {e$message}"
            ))
            "[OUTPUT CAPTURE FAILED]"
          }
        )
      } else {
        ""
      }
    },

    #' Truncate output to max size
    truncate_output = function(text) {
      if (nchar(text) > self$max_output_chars) {
        paste0(
          substr(text, 1, self$max_output_chars),
          "\n... [TRUNCATED - exceeded ",
          self$max_output_chars,
          " characters]"
        )
      } else {
        text
      }
    },

    #' Create an error result structure
    error_result = function(
      error,
      stdout = "",
      stderr = "",
      messages = "",
      warnings = "",
      duration_ms = 0
    ) {
      list(
        success = FALSE,
        result = NULL,
        stdout = private$truncate_output(stdout),
        stderr = private$truncate_output(stderr),
        messages = messages,
        warnings = warnings,
        error = error,
        duration_ms = round(duration_ms, 2)
      )
    }
  )
)
