#' R Code Execution Backend
#'
#' @description
#' A subprocess execution backend for running R code generated by LLMs. Uses
#' callr for process isolation, timeout protection, output capture, and
#' structured result handling.
#'
#' @details
#' RCodeRunner provides:
#' - **Process isolation**: Code runs in a separate R process via callr
#' - **Timeout protection**: Configurable timeout prevents runaway execution
#' - **Output capture**: Captures stdout, stderr, messages, and warnings
#' - **Context passing**: Inject data into the execution environment
#' - **Output limiting**: Truncates large outputs to prevent memory issues
#'
#' Security note: `r_code_runner()` is a **trusted-input-only** backend. callr
#' starts a separate process, but that process retains the host user's file,
#' network, environment, and operating-system permissions. Pattern checks are
#' only defense in depth and can be bypassed. For untrusted inputs, provide a
#' runner backed by a container or OS-level sandbox.
#'
#' Code-executing modules accept any runner that implements the dsprrr runner
#' protocol. A runner must expose `execute(code, context = list())` and
#' `policy()` methods. `policy()` returns a named list containing at least
#' `backend` (character), `trust` (character), and `sandboxed` (logical).
#' `execute()` returns a list with `success`, `result`, `stdout`, `stderr`,
#' `messages`, `warnings`, `error`, and `duration_ms` fields.
#'
#' @examples
#' \dontrun{
#' runner <- r_code_runner(timeout = 5)
#'
#' # Simple execution
#' result <- runner$execute("1 + 1")
#' result$result
#' # [1] 2
#'
#' # With context
#' result <- runner$execute(
#'   "mean(.context$data$mpg)",
#'   context = list(data = mtcars)
#' )
#' result$result
#' # [1] 20.09062
#'
#' # Timeout handling
#' result <- runner$execute("Sys.sleep(100)")
#' result$success
#' # [1] FALSE
#' result$error
#' # "Execution timed out after 5 seconds"
#' }
#'
#' @name r-code-runner
NULL

#' Create an R Code Runner
#'
#' @description
#' Factory function to create a trusted-input-only RCodeRunner instance.
#'
#' @param timeout Numeric. Maximum execution time in seconds. Default 30.
#' @param max_output_chars Integer. Maximum characters for stdout/stderr.
#'   Output exceeding this limit is truncated. Default 100000 (100KB).
#' @param allowed_packages Character vector. Packages that may be loaded.
#'   This is defense-in-depth only; not a security boundary.
#'
#'   Default: c("base", "stats", "utils", "methods").
#' @param prelude Character vector. R code to run before user code.
#'   Useful for setting options or loading common utilities.
#'
#' @return An RCodeRunner R6 object
#'
#' @export
#' @examples
#' \dontrun{
#' runner <- r_code_runner(timeout = 10)
#' result <- runner$execute("sqrt(16)")
#' result$result
#' # [1] 4
#' }
r_code_runner <- function(
  timeout = 30,
  max_output_chars = 100000L,
  allowed_packages = c("base", "stats", "utils", "methods"),
  prelude = character()
) {
  rlang::check_installed("callr", reason = "for code execution")

  RCodeRunner$new(
    timeout = timeout,
    max_output_chars = as.integer(max_output_chars),
    allowed_packages = allowed_packages,
    prelude = prelude
  )
}


# Validate the structural runner protocol used by code-executing modules.
validate_code_runner <- function(runner) {
  execute <- tryCatch(runner[["execute"]], error = function(e) NULL)
  policy <- tryCatch(runner[["policy"]], error = function(e) NULL)

  if (!is.function(execute) || !is.function(policy)) {
    cli::cli_abort(c(
      "runner must implement the dsprrr code-runner protocol",
      "x" = "A runner needs {.code execute(code, context)} and {.code policy()} methods.",
      "i" = "Use {.code r_code_runner()} for trusted inputs or provide a sandboxed backend."
    ))
  }

  runner_policy <- tryCatch(
    policy(),
    error = function(e) {
      cli::cli_abort(c(
        "runner$policy() failed",
        "x" = conditionMessage(e)
      ))
    }
  )
  required <- c("backend", "trust", "sandboxed")
  missing_fields <- setdiff(required, names(runner_policy))

  if (!is.list(runner_policy) || length(missing_fields) > 0) {
    cli::cli_abort(c(
      "runner$policy() must return a named list",
      "x" = "Missing required fields: {.field {missing_fields}}",
      "i" = "Required fields are {.field backend}, {.field trust}, and {.field sandboxed}."
    ))
  }

  valid_backend <- is.character(runner_policy$backend) &&
    length(runner_policy$backend) == 1L &&
    !is.na(runner_policy$backend) &&
    nzchar(runner_policy$backend)
  valid_trust <- is.character(runner_policy$trust) &&
    length(runner_policy$trust) == 1L &&
    !is.na(runner_policy$trust) &&
    nzchar(runner_policy$trust)
  valid_sandboxed <- is.logical(runner_policy$sandboxed) &&
    length(runner_policy$sandboxed) == 1L &&
    !is.na(runner_policy$sandboxed)

  if (!valid_backend || !valid_trust || !valid_sandboxed) {
    cli::cli_abort(c(
      "runner$policy() returned invalid metadata",
      "i" = "{.field backend} and {.field trust} must be non-empty strings.",
      "i" = "{.field sandboxed} must be TRUE or FALSE."
    ))
  }

  invisible(runner)
}


#' RCodeRunner R6 Class
#'
#' @description
#' R6 class for trusted R code execution in separate subprocesses.
#'
#' TRUST NOTE: This class intentionally uses eval() to execute
#' LLM-generated R code. This is the core purpose of the ProgramOfThought
#' and CodeAct modules. It provides operational safeguards through:
#' 1. Opt-in design (requires explicit runner creation)
#' 2. Subprocess isolation via callr
#' 3. Timeout protection
#' 4. Dangerous pattern scanning (defense in depth)
#'
#' These safeguards do not restrict host permissions and are not a security
#' boundary. For untrusted input, provide a runner backed by OS-level sandboxing.
#'
#' @keywords internal
#' @noRd
RCodeRunner <- R6::R6Class(
  "RCodeRunner",
  public = list(
    #' @field timeout Maximum execution time in seconds
    timeout = NULL,

    #' @field max_output_chars Maximum output size before truncation
    max_output_chars = NULL,

    #' @field allowed_packages Packages allowed to be loaded
    allowed_packages = NULL,

    #' @field prelude Code to run before user code
    prelude = NULL,

    #' @description
    #' Initialize a new RCodeRunner
    #' @param timeout Numeric timeout in seconds
    #' @param max_output_chars Integer max output size
    #' @param allowed_packages Character vector of allowed packages
    #' @param prelude Character vector of prelude code
    initialize = function(
      timeout = 30,
      max_output_chars = 100000L,
      allowed_packages = c("base", "stats", "utils", "methods"),
      prelude = character()
    ) {
      self$timeout <- timeout
      self$max_output_chars <- max_output_chars
      self$allowed_packages <- allowed_packages
      self$prelude <- prelude
    },

    #' @description
    #' Execute R code in an isolated subprocess
    #'
    #' @param code Character string of R code to execute
    #' @param context Named list of objects to make available as `.context`
    #'
    #' @return A list with components:
    #'   - `success`: Logical indicating successful execution
    #'   - `result`: The return value of the code (NULL on error)
    #'   - `stdout`: Character string of stdout output
    #'   - `stderr`: Character string of stderr output
    #'   - `messages`: Character string of message() output
    #'   - `warnings`: Character string of warning() output
    #'   - `error`: Error message if failed (NULL on success)
    #'   - `duration_ms`: Execution time in milliseconds
    execute = function(code, context = list()) {
      if (!is.character(code) || length(code) != 1) {
        cli::cli_abort("code must be a single character string")
      }

      start_time <- Sys.time()

      # Check for dangerous patterns (defense in depth)
      danger_check <- private$check_dangerous_patterns(code)
      if (!is.null(danger_check)) {
        return(private$error_result(
          error = danger_check,
          duration_ms = 0
        ))
      }

      # Create temp files for output capture
      stdout_file <- tempfile("stdout_", fileext = ".txt")
      stderr_file <- tempfile("stderr_", fileext = ".txt")
      on.exit(unlink(c(stdout_file, stderr_file)), add = TRUE)

      # Build the execution wrapper
      exec_result <- tryCatch(
        {
          callr::r(
            func = private$execution_wrapper,
            args = list(
              code = code,
              context = context,
              prelude = self$prelude,
              allowed_packages = self$allowed_packages
            ),
            timeout = self$timeout,
            stdout = stdout_file,
            stderr = stderr_file,
            user_profile = FALSE,
            env = c(
              callr::rcmd_safe_env(),
              "R_BROWSER" = "false",
              "R_PDFVIEWER" = "false"
            )
          )
        },
        callr_timeout_error = function(e) {
          structure(
            list(
              error = paste0(
                "Execution timed out after ",
                self$timeout,
                " seconds"
              )
            ),
            class = "timeout_error"
          )
        },
        system_command_timeout_error = function(e) {
          structure(
            list(
              error = paste0(
                "Execution timed out after ",
                self$timeout,
                " seconds"
              )
            ),
            class = "timeout_error"
          )
        },
        error = function(e) {
          structure(
            list(error = conditionMessage(e)),
            class = "exec_error"
          )
        }
      )

      duration_ms <- as.numeric(
        difftime(Sys.time(), start_time, units = "secs")
      ) *
        1000

      # Read captured output
      stdout_content <- private$read_output_file(stdout_file)
      stderr_content <- private$read_output_file(stderr_file)

      # Handle different result types
      if (inherits(exec_result, "timeout_error")) {
        return(private$error_result(
          error = exec_result$error,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms
        ))
      }

      if (inherits(exec_result, "exec_error")) {
        return(private$error_result(
          error = exec_result$error,
          stdout = stdout_content,
          stderr = stderr_content,
          duration_ms = duration_ms
        ))
      }

      # Successful execution - exec_result is the wrapper's return value
      list(
        success = exec_result$success,
        result = exec_result$result,
        stdout = private$truncate_output(stdout_content),
        stderr = private$truncate_output(stderr_content),
        messages = private$truncate_output(exec_result$messages %||% ""),
        warnings = private$truncate_output(exec_result$warnings %||% ""),
        error = exec_result$error,
        duration_ms = round(duration_ms, 2)
      )
    },

    #' @description
    #' Describe the execution backend's trust boundary
    #'
    #' @return A named list implementing the dsprrr runner policy contract
    policy = function() {
      list(
        backend = "callr",
        trust = "trusted-input-only",
        sandboxed = FALSE,
        process_isolation = TRUE,
        filesystem_access = "host-user",
        network_access = "host-user",
        pattern_scan = "defense-in-depth"
      )
    },

    #' @description
    #' Print method for RCodeRunner
    print = function() {
      trust <- self$policy()$trust
      cli::cli_h3("RCodeRunner")
      cli::cli_bullets(c(
        "*" = "Timeout: {.val {self$timeout}} seconds",
        "*" = "Max output: {.val {self$max_output_chars}} chars",
        "*" = "Allowed packages: {.val {self$allowed_packages}}",
        "!" = "Trust: {.val {trust}}; not sandboxed"
      ))
      invisible(self)
    }
  ),

  private = list(
    #' Wrapper function that runs inside the subprocess
    #' NOTE: Intentionally uses eval() - this is the core purpose of
    #' ProgramOfThought/CodeAct modules (execute LLM-generated code)
    execution_wrapper = function(code, context, prelude, allowed_packages) {
      # Capture messages and warnings
      messages <- character()
      warnings <- character()

      result <- tryCatch(
        {
          # Set up message/warning handlers
          withCallingHandlers(
            {
              # Make context available
              .context <- context

              # Create execution environment with context
              exec_env <- new.env(parent = globalenv())
              exec_env$.context <- context

              # Override library/require to enforce allowed_packages
              exec_env$library <- function(package, ...) {
                pkg_expr <- substitute(package)
                pkg_name <- if (is.character(pkg_expr)) {
                  pkg_expr
                } else {
                  as.character(pkg_expr)
                }
                if (!pkg_name %in% allowed_packages) {
                  stop(
                    "Package '",
                    pkg_name,
                    "' is not in allowed_packages. ",
                    "Allowed: ",
                    paste(allowed_packages, collapse = ", "),
                    call. = FALSE
                  )
                }
                base::library(pkg_name, character.only = TRUE, ...)
              }

              exec_env$require <- function(package, ...) {
                pkg_expr <- substitute(package)
                pkg_name <- if (is.character(pkg_expr)) {
                  pkg_expr
                } else {
                  as.character(pkg_expr)
                }
                if (!pkg_name %in% allowed_packages) {
                  stop(
                    "Package '",
                    pkg_name,
                    "' is not in allowed_packages. ",
                    "Allowed: ",
                    paste(allowed_packages, collapse = ", "),
                    call. = FALSE
                  )
                }
                base::require(pkg_name, character.only = TRUE, ...)
              }

              # Run prelude if any
              if (length(prelude) > 0) {
                for (p in prelude) {
                  base::eval(base::parse(text = p), envir = exec_env)
                }
              }

              # Evaluate the user code - this is intentional for code execution
              # Operational safeguards are subprocess isolation, timeout, and
              # pattern checks. They are not a security boundary.
              base::eval(base::parse(text = code), envir = exec_env)
            },
            message = function(m) {
              messages <<- c(messages, conditionMessage(m))
              invokeRestart("muffleMessage")
            },
            warning = function(w) {
              warnings <<- c(warnings, conditionMessage(w))
              invokeRestart("muffleWarning")
            }
          )
        },
        error = function(e) {
          structure(
            list(msg = conditionMessage(e)),
            class = "code_error"
          )
        }
      )

      if (inherits(result, "code_error")) {
        list(
          success = FALSE,
          result = NULL,
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = result$msg
        )
      } else {
        list(
          success = TRUE,
          result = result,
          messages = paste(messages, collapse = "\n"),
          warnings = paste(warnings, collapse = "\n"),
          error = NULL
        )
      }
    },

    #' Check for dangerous code patterns (defense in depth)
    check_dangerous_patterns = function(code) {
      # Note: This is NOT a security boundary, just defense in depth
      # Real security requires OS-level sandboxing

      dangerous_patterns <- list(
        # System access (including base:: prefix bypass attempts)
        "(?:base::)?system\\s*\\(" = "system() calls are not allowed",
        "(?:base::)?system2\\s*\\(" = "system2() calls are not allowed",
        "(?:base::)?Sys\\.setenv" = "Modifying environment variables is not allowed",

        # do.call bypass attempts
        "do\\.call\\s*\\(\\s*['\"]?system" = "do.call(system) is not allowed",
        "do\\.call\\s*\\(\\s*['\"]?system2" = "do.call(system2) is not allowed",

        # File system (destructive operations)
        "(?:base::)?unlink\\s*\\(" = "unlink() is not allowed",
        "(?:base::)?file\\.remove" = "file.remove() is not allowed",

        # Process control
        "(?:base::)?quit\\s*\\(" = "quit() is not allowed",
        "(?:base::)?q\\s*\\(\\s*\\)" = "q() is not allowed",

        # Network (basic check)
        "(?:utils::)?download\\.file" = "download.file() is not allowed",
        "(?:base::)?url\\s*\\(" = "url() connections are not allowed"
      )

      for (pattern in names(dangerous_patterns)) {
        if (grepl(pattern, code, ignore.case = FALSE, perl = TRUE)) {
          return(paste0(
            "Dangerous pattern detected: ",
            dangerous_patterns[[pattern]]
          ))
        }
      }

      NULL
    },

    #' Read and handle output file
    read_output_file = function(filepath) {
      if (file.exists(filepath)) {
        tryCatch(
          paste(readLines(filepath, warn = FALSE), collapse = "\n"),
          error = function(e) {
            cli::cli_warn(c(
              "Failed to read subprocess output",
              "x" = "Error: {e$message}"
            ))
            "[OUTPUT CAPTURE FAILED]"
          }
        )
      } else {
        ""
      }
    },

    #' Truncate output to max size
    truncate_output = function(text) {
      if (nchar(text) > self$max_output_chars) {
        paste0(
          substr(text, 1, self$max_output_chars),
          "\n... [TRUNCATED - exceeded ",
          self$max_output_chars,
          " characters]"
        )
      } else {
        text
      }
    },

    #' Create an error result structure
    error_result = function(
      error,
      stdout = "",
      stderr = "",
      messages = "",
      warnings = "",
      duration_ms = 0
    ) {
      list(
        success = FALSE,
        result = NULL,
        stdout = private$truncate_output(stdout),
        stderr = private$truncate_output(stderr),
        messages = messages,
        warnings = warnings,
        error = error,
        duration_ms = round(duration_ms, 2)
      )
    }
  )
)
