http_interactions:
- request:
    method: POST
    uri: https://api.openai.com/v1/responses
  response:
    status: 200
    headers:
      alt-svc: h3=":443"; ma=86400
      cf-cache-status: DYNAMIC
      cf-ray: 9b8ca9764a8f6129-ORD
      content-encoding: gzip
      content-type: application/json
      date: Sun, 04 Jan 2026 18:05:04 GMT
      openai-organization: james-wade-gxavj5
      openai-processing-ms: '512'
      openai-project: proj_52QUMhtrLoBeFWjuGQhiv2ox
      openai-version: '2020-10-01'
      server: cloudflare
      set-cookie:
      - __cf_bm=4h7ZcD5wiQtQTnjGzY7tGSkRcQs3XRWy7nDsGIza7ZA-1767549904-1.0.1.1-7WpOt7OEYukwPOQHEC0nYsyFaI3z_q32dYTy96eUvZMxuIKxHZxGeXyi3qwmJGymjCAD4u.G55WfNlhoxPLNqtlLnOiMnn6EvsXyZDGIW9Y;
        path=/; expires=Sun, 04-Jan-26 18:35:04 GMT; domain=.api.openai.com; HttpOnly;
        Secure; SameSite=None
      - _cfuvid=TfS2g0_..W_H2E0Mw_6FAjaR9ZMK5gNu1G82HWVRr4M-1767549904941-0.0.1.1-604800000;
        path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None
      strict-transport-security: max-age=31536000; includeSubDomains; preload
      x-content-type-options: nosniff
      x-envoy-upstream-service-time: '516'
      x-ratelimit-limit-requests: '500'
      x-ratelimit-limit-tokens: '30000'
      x-ratelimit-remaining-requests: '499'
      x-ratelimit-remaining-tokens: '30000'
      x-ratelimit-reset-requests: 120ms
      x-ratelimit-reset-tokens: 0s
      x-request-id: req_335dd753d5404d68bdbf4981bd9bde43
    body:
      string: |-
        {
          "id": "resp_02e9a6301ce2b1e901695aabd068e48197b7d67e9edb807943",
          "object": "response",
          "created_at": 1767549904,
          "status": "completed",
          "background": false,
          "billing": {
            "payer": "developer"
          },
          "completed_at": 1767549904,
          "error": null,
          "incomplete_details": null,
          "instructions": null,
          "max_output_tokens": null,
          "max_tool_calls": null,
          "model": "gpt-4.1-2025-04-14",
          "output": [
            {
              "id": "msg_02e9a6301ce2b1e901695aabd0d3b081979daf06d4e618cd57",
              "type": "message",
              "status": "completed",
              "content": [
                {
                  "type": "output_text",
                  "annotations": [],
                  "logprobs": [],
                  "text": "{\"wrapper\":\"negative\"}"
                }
              ],
              "role": "assistant"
            }
          ],
          "parallel_tool_calls": true,
          "previous_response_id": null,
          "prompt_cache_key": null,
          "prompt_cache_retention": null,
          "reasoning": {
            "effort": null,
            "summary": null
          },
          "safety_identifier": null,
          "service_tier": "default",
          "store": false,
          "temperature": 1.0,
          "text": {
            "format": {
              "type": "json_schema",
              "description": null,
              "name": "structured_data",
              "schema": {
                "type": "object",
                "description": "",
                "properties": {
                  "wrapper": {
                    "type": "string",
                    "description": ""
                  }
                },
                "required": [
                  "wrapper"
                ],
                "additionalProperties": false
              },
              "strict": true
            },
            "verbosity": "medium"
          },
          "tool_choice": "auto",
          "tools": [],
          "top_logprobs": 0,
          "top_p": 1.0,
          "truncation": "disabled",
          "usage": {
            "input_tokens": 124,
            "input_tokens_details": {
              "cached_tokens": 0
            },
            "output_tokens": 6,
            "output_tokens_details": {
              "reasoning_tokens": 0
            },
            "total_tokens": 130
          },
          "user": null,
          "metadata": {}
        }
  recorded_at: 2026-01-04 18:05:04
recorded_with: VCR-vcr/2.1.0
